### ISSUE TITLE
Yarn installs previous version

### ISSUE THREAD

**Issue by JohnPaulHarold** [maxmarinich/react-alice-carousel#10]
When I `yarn add ` this package, I get version `1.7.1` according to the `package.json`, as opposed to what's in master currently. Could you push the latest to `npm`?

**Comment by maxmarinich** [comment]
Updated to [1.7.2](https://www.npmjs.com/package/react-alice-carousel)

**Comment by JohnPaulHarold** [comment]
@maxmarinich I'm a bit confused what's happening here. The `package.json` that comes down via yarn is different to what's in the repo currently. What comes down via `yarn` expects `gulp` scripts, and a compiled build in `lib`. Does that sound correct?

**Comment by maxmarinich** [comment]
You're right! Current version is 1.7.3. I've add new feature after npm
updated. New version will be uploaded today.
