### ISSUE TITLE
Carousel displaying two items instead of one

### ISSUE THREAD

**Issue by Sashkan** [maxmarinich/react-alice-carousel#101]
I'm trying to display 3 images, but the slides behave oddly.

My Carousel is very basic:

```js

          <Carousel
            sliderSettings={sliderSettings}
            slideIndex={slideIndex}
          >
            {zones.map(zone => (
              <div className='sliderElement'>
                <ProductImage
                  alt={`${product._id}-img`}
                  product={product}
                />
              </div>
            ))}
          </Carousel>
```

it's supposed to display 3 images. 
Unfortunately, this results in the following:

![Peek 2019-12-20 11-53](https://user-images.githubusercontent.com/6276267/71250212-61345780-231f-11ea-9b17-dac1323f986b.gif)

As you can see, the first image is displayed just fine, but the second slide is empty, and the 3rd slide includes both the 2nd and 3rd image !

How comes so ?

I also tried with the `items` prop, but this makes it even worst: nothing  gets displayed, Carousel DOM element is just an empty `ul` tag.

If anything, please note that the 2nd and 3rd images are SVGs, and not img.

**Comment by maxmarinich** [comment]
Hi, @Sashkan! I've confused a little by your example) Please, provide the code like [this](https://codesandbox.io/s/react-alice-carousel-stage-padding-example-wk21f).
