### ISSUE TITLE
How to force re-initialising of item width for carousel?

### ISSUE THREAD

**Issue by lqze** [maxmarinich/react-alice-carousel#106]
Hello,

I'm trying to see if there is way to force the re-calculation of the item width size based off window resize.

On initialisation I can see the gallery get's created and the item width is responsive based off the initialisation, but is there a way to force a re-initialisation so the initial item width is re-calculated?

Thank you.

**Comment by maxmarinich** [comment]
Hi, @lqze! There's not. But you can use workaround:
```javascript
// use refs
ref._setInitialState()

// trigger resize event, what will run `_handleOnWindowResize` method
window.dispatchEvent(new Event('resize'))

```
