### ISSUE TITLE
Feature Request: Custom transition timing function

### ISSUE THREAD

**Issue by romiem** [maxmarinich/react-alice-carousel#114]
Hi Max,

Any chance you would consider allowing users to specify a custom transition-timing-function? I noticed in the utils/animation.js and utils/style.js files that "ease-out" is hardcoded. I imagine you could probably add a new prop type called transitionTimingFunction and have it's default value set to ease-out to maintain compatibility.

Thank you!

**Comment by maxmarinich** [comment]
Hi, @romiem! Why not.  Will be implemented in the next version.

**Comment by maxmarinich** [comment]
Implemented in #116

**Comment by romiem** [comment]
Hey - I've just noticed that the index.d.ts file has not been updated to include this new property. Would you mind adding it please?

**Comment by maxmarinich** [comment]
Hi, @romiem, thanks so much for the comment! Fixed in #124 .
