### ISSUE TITLE
Cannot read property 'bool' of undefined

### ISSUE THREAD

**Issue by Ulzhan** [maxmarinich/react-alice-carousel#115]
./node_modules/react-alice-carousel/lib/prop-types.js

  12 | function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
  13 | 
  14 | var propTypes = exports.propTypes = {
> 15 |   autoHeight: _propTypes2.default.bool,

**Comment by maxmarinich** [comment]
Hi, @Ulzhan! Try: 
```
rm -rf node_modules
yarn cache clean --force; npm cache clean --force
npm i
```
or provide a correct code sample

**Comment by Ulzhan** [comment]
Unfortunately it still doesn't work. 
Code example is the same as your example: 
  const sliderRef = useRef<AliceCarousel>(null);
  const elms = [1, 2, 3, 4, 5];
  const items = elms.map(i => <h2 key={i}>{i}</h2>);
  return (
    <div className={classNames(className, 'py-2')}>
      <AliceCarousel
        dotsDisabled={true}
        buttonsDisabled={true}
        items={items}
        ref={sliderRef}
        autoHeight
      />
      <button onClick={() => sliderRef?.current?.slidePrev()}>Prev button</button>
      <button onClick={() => sliderRef?.current?.slideNext()}>Next button</button>
    </div>
  );

**Comment by maxmarinich** [comment]
Not reproduced. Looks like not library issue. Use [this](https://codesandbox.io/s/reactalicecarousel-typescript-example-y7obi) live `ts` example.
