### ISSUE TITLE
Continuous animations without pausing

### ISSUE THREAD

**Issue by rramphal** [maxmarinich/react-alice-carousel#118]
Thanks, @maxmarinich, for your great work on this!

I was wondering if there is any way to get completely smooth, continuous animations without the pauses between each step.

This configuration gets us really close,

```jsx
<AliceCarousel
  ...
  duration={5000} /* some high value here */
  transitionTimingFunction="linear"
  autoPlay
  infinite
/>
```

but there is still a pause between each step. I'm about to start reading the code, but I thought I'd ask you here in case you know off the top of your head.

**Comment by maxmarinich** [comment]
Hi, @rramphal! You're right! The autoplay feature looks a bit inelegant. And will be improved in future releases.

**Comment by rardoz** [comment]
set autoPlayInterval to 0 stops the pausing between slides.

**Comment by rramphal** [comment]
Thanks @rardoz! Did you happen to see behavior where the carousel suddenly runs backwards and starts the animations again when setting `autoPlayInterval={0}`?

**Comment by samp101** [comment]
Yes I have is there a way to fix it?
After 3 times of running through the images the carousel moves back and restarts again as if.

```
 <DynamicAliceCarousel
        infinite
        autoPlayInterval={0}
        animationDuration={2000}
        animationEasingFunction="linear"
        autoPlay
/>
```
