### ISSUE TITLE
Going back to initial slide on click

### ISSUE THREAD

**Issue by knowBalpreet** [maxmarinich/react-alice-carousel#12]
Hi,
I am using this component to render different images from which user can chose and select . If user is on third slide and clicks on any image. It goes back to first slide. Dont know how to fix it. Any help will be appreciated

**Comment by maxmarinich** [comment]
Could you provide the code sample?

**Comment by knowBalpreet** [comment]
Hi,
Thanks for such a quick revert. I fixed this problem by setting slideToIndex with refs. 
I am stuck at the problem where data changes and doesnt reflects in carousel.
It is not rerendering on changing data. If i add unique key to fix it. My initial logic to stay on current slide fails.

`            <AliceCarousel
              responsive={responsive}
              fadeOutAnimation={true}
              autoPlayActionDisabled={true}
              slideToIndex = {this.state.currentIndex}
              ref = 'slider'
              >
              {this.state.data.elements.map((val, key) => <div key={key}><img className="img-thumbnail card-img-top" onClick={() => this.addSelected(val.img)} src={val.img} /></div>)}
            </AliceCarousel>`

`  addSelected(val){
    let selected = this.state.selected;
    if (selected.indexOf(val) === -1){
      selected.push(val);
      this.setState({ selected, currentIndex:this.refs.slider.state.currentIndex })
    }
  }`

**Comment by maxmarinich** [comment]
Please, provide code where you've got an unexpected behavior.

**Comment by knowBalpreet** [comment]
Updated the previous question

**Comment by maxmarinich** [comment]
It looks like you pass incorrect value to the `slideToIndex` property. There's an example how to use gallery-thumbs with props (see readme). If you'll not resolve the problem, create a simple repo with not working example(full example) and give me know. 
So, small advice: never mutate objects when use react.  I'm about next:

**Comment by maxmarinich** [comment]
So, small advice: never mutate objects when use react.  I'm about next: ``

**Comment by maxmarinich** [comment]
So, small advice: never mutate objects when use react.  I'm about next: 
`let selected = this.state.selected`
