### ISSUE TITLE
playButtonEnabled Not working right!

### ISSUE THREAD

**Issue by HadeerFawzy** [maxmarinich/react-alice-carousel#120]
Hello, I just started recently to try out your library and I noticed that the `playButtonEnabled ` property doesn't work right, it works fine at the first click on it and when I hit stop it stops but then it doesn't work ever again no matter how many times I click on the button! 
Also, I tried to use it with the `autoPlay` and once I hit stop and try to make it work again it doesn't respond!

**Comment by maxmarinich** [comment]
Hi, @HadeerFawzy! Thank for the report. The issue was fixed here #122 . Please update to [v1.19](https://www.npmjs.com/package/react-alice-carousel).
