### ISSUE TITLE
After resizing carousel always shows first slide

### ISSUE THREAD

**Issue by excyted** [maxmarinich/react-alice-carousel#121]
Hi  @maxmarinich ,

Really cool library. Thanks a lot for sharing it.

I don't know if it's intentional but after resizing the browser window and thereby resizing the carousel container it always shows the first slide again no matter what slide was previously shown. Also thereby after resizing the `currentIndex` state of the parent component and AliceCarousel are not in sync anymore. Only after changing the `currentIndex` state in the parent component to a different index by using `slideTo` or `slideNext`/`slidePrev` methods they are in sync again.

Is there a way to stay on the current Slide after resizing?

**Comment by maxmarinich** [comment]
Hi, @excyted! This is an expected behavior. When the stage was changed (resized), it means that the user changed something, such as rotate the device. In this case, we don't have to care about the animation or anything else, because the user forcibly changed the previous state.

For consistent state you should save `currentIndex` in the parent and after `onResized ` event run `slideTo(currentIndex)` or pass/update `slideToIndex = currentIndex` prop.

In the upcoming version, I will add a more convenient flow for this.

**Comment by excyted** [comment]
Thanks for your reply @maxmarinich. So are you saying it is possible to stay on the current slide after resizing or sliding to it again immediately after? Because I have setup my parent the way you describe and it is not working. The `currentIndex` is saved in the parent's state and is passed as a value to the `slideToIndex` prop of the carousel. When I also add `onResized={this.slideTo(currentIndex)}` as a prop i get the following error: Maximum update depth exceeded.

**Comment by maxmarinich** [comment]
It's better use `slideToIndex`.  Also there's a typo, of course if you don't use the currying inside `slideTo` method.
As workaround only(because refs):
```js
onResized={() => this.slideTo(currentIndex)}
// or
onResized={() => setTimeout(() => this.slideTo(currentIndex))}
```

**Comment by excyted** [comment]
Still not working because the `currentIndex` state doesn't change by doing that. The `currentState` of the parent has to change to a different value first to be consistent with the carousel again. So this workaround works:

```
handleResize = () => {
    this.setState({ currentIndex: this.state.currentIndex + 1 })
    setTimeout(() => {
      this.setState({ currentIndex: this.state.currentIndex - 1 })
    }, 260)
  }

<AliceCarousel
    slideToIndex={currentIndex}
    onSlideChanged={this.onSlideChanged}
    items={galleryItems}
    onResized={this.handleResize}
/>
```

**Comment by maxmarinich** [comment]
The better way is:
```js
  state = {
    currentIndex: 0,
    slideToIndex: 0,
  }

  onSlideChanged = ({ item }) => {
    this.setState({ currentIndex: item })
  }

  onResized = () => {
    const { currentIndex } = this.state
    this.setState({ slideToIndex: currentIndex })
  }

```
and 
```js
  <AliceCarousel
    slideToIndex={this.state.slideToIndex}
    onSlideChanged={this.onSlideChanged}
    onResized={this.onResized}
  >
```

**Comment by excyted** [comment]
But that is not getting rid of the problem. The workaround I posted works for me so far.

**Comment by maxmarinich** [comment]
@maxmarinich please update to v1.19. The `preservePosition` property should resolve your case.

**Comment by excyted** [comment]
Oh wow thanks a lot for the quick fix!! You're awesome!
