### ISSUE TITLE
Slides not updating when using with react-router and changing route

### ISSUE THREAD

**Issue by oskar-kupski-valueadd** [maxmarinich/react-alice-carousel#13]
Hi there,

I have a strange issue with changing slides. I have a website that uses alice-carousel on few subpages. The issue is:
1. I load the page with component that uses alice-slider
2. I go to another subpage with the same component, but I pass different slides.
3. On that page new slides are passed, but somehow slides from previous page are displayed.

I double checked passed data, and when I display slides withous slider ( just in raw div ) everything works, so it's probably library issue.

Could you please help me with this one?

**Comment by oskar-kupski-valueadd** [comment]
I created pull request for this issue, please see it

**Comment by maxmarinich** [comment]
Thank's @oskar-kupski-valueadd, please review the issue.
Fixed in [f9f4e8b](https://github.com/maxmarinich/react-alice-carousel/commit/f9f4e8bf7a847c772f7c14185dea4bd403a382c8)
