### ISSUE TITLE
iPhone 11 Safari mobile - slide will sometimes get stuck during transition when using touch controls

### ISSUE THREAD

**Issue by markdegroat** [maxmarinich/react-alice-carousel#130]
iPhone 11 Safari mobile - slide will sometimes get stuck during transition when using touch controls
It seems as if it's getting stuck at the exact middle point between the two different slides.  Sending another swipe/touch event after it gets stuck fixes the issue.  Only reproducible on iPhone 11's - not iPhone X's.

**Comment by maxmarinich** [comment]
Hi, @markdegroat! Could you clarify the issue with the video or code sample?

**Comment by maxmarinich** [comment]
Hi, @markdegroat! Fixed in v2. Please check live [demo](https://maxmarinich.github.io/react-alice-carousel/static) and new version of library.
