### ISSUE TITLE
Using slidePrev() & slideNext() methods in functional components

### ISSUE THREAD

**Issue by simonrevill** [maxmarinich/react-alice-carousel#132]
I don't want to render the buttons in my carousel. I need to trigger the `slidePrev()` & `slideNext()` methods on another element. Is there a way I can access these methods apart from using the refs? The examples in the docs only use class-based components, and my component is functional.

Many thanks

**Comment by maxmarinich** [comment]
Hi, @simonrevill! You can use props like in [example](https://github.com/maxmarinich/react-alice-carousel#custom-prev--next-buttons-dots--thumbs-navigation). Or redefine the default css classes for buttons, they are very flexible to configure.

**Comment by mercteil** [comment]
You can use forwardRef to register the reference:

```javascript
const Carousel = forwardRef((props, ref) => {

  return (
      <AliceCarousel
        ref={ref}
        ....
```

and use it within the parent component

```javascript
const ProductGallery = (props) => {
  const carouselRef = useRef(null);

  return (
      <Carousel
        ref={carouselRef}
        ...


   // from here carouselRef has access to carouselRef.current.slideTo, carouselRef.current.slideNext, carouselRef.current.slidePrev methods etc.

```

**Comment by mohit810** [comment]
hey, its not working even if using exact code from example..
