### ISSUE TITLE
slideToIndex not working with props

### ISSUE THREAD

**Issue by simonrevill** [maxmarinich/react-alice-carousel#133]
I have an issue where I can't get the carousel to change index when the props change. If I change the index manually inside the React Components DevTools, it will slide to the image at the index specified. However, when the props change, I see the change in the DevTools, but the carousel does not slide. Here's my code with some comments:

```javascript
import React from 'react';
import AliceCarousel from 'react-alice-carousel';
import '../../../node_modules/react-alice-carousel/lib/alice-carousel.css';

class MainLibraryCarousel extends React.Component {

  render() {

    // get currently selected image from the props:
    const { imageLibrary, currentSelectedImage } = this.props;

   // get the the index number from the currentSelectedImage:
    const currentIndex = imageLibrary.findIndex(image => image.id === currentSelectedImage.id);

    return (
        <AliceCarousel
          mouseTrackingEnabled={true}
          items={imageLibrary.map((image, index) => (
            <div
              key={image.id}
              className={image.id === currentSelectedImage.id ? 'carousel__image carousel__image--selected' : 'carousel__image'}
              style={{
                backgroundImage: `url("${image.url}")`,
                backgroundSize: 'cover',
                backgroundPosition: 'center center',
                backgroundRepeat: 'no-repeat',
                width: '330px',
                height: '330px',
                display: 'inline-block'
              }}
            />
          ))}
          dotsDisabled={true}
          duration={250}
          buttonsDisabled={false}
          // Here I'm passing the currentIndex variable (number) to slideToIndex:
          slideToIndex={currentIndex}
        />
       
       /* ... */
    )
  }
};

export default MainLibraryCarousel;
```

**Comment by maxmarinich** [comment]
Hi, @simonrevill! The problem is here `items ={imageLibrary.map((image, index) => (...`. Because every time you get a new props, items are also created as a new object(props). And the carousel is updated after them checking. In your case use `startIndex` instead `slideToIndex `, or do a refactoring of the component. Check and let me know the result please.

**Comment by simonrevill** [comment]
Thank you for the quick reply, Max. I've tried using `startIndex` instead:

![no-css-transforms](https://user-images.githubusercontent.com/34922287/86590044-aef47280-bf86-11ea-8014-e25425c52a51.gif)

This does work, but the problem is that I no longer get the nice CSS transforms / animations like before.

**Comment by maxmarinich** [comment]
You should not mutate `items`, save them in the state. Please, see [example](https://github.com/maxmarinich/react-alice-carousel#example-for-slideprevslidenext-page).
