### ISSUE TITLE
Responsive prop is causing carousel to reset

### ISSUE THREAD

**Issue by jaketrimble** [maxmarinich/react-alice-carousel#134]
Anytime the responsive prop is added, the carousel randomly resets after a slide change. It doesn't even fire the onSlideChange or onSlideChanged functions. Anyone else experiencing this?

Even using `responsive` like in the example, causes the reset to happen after executing a slide.
```
{
      0: {
          items: 1,
      },
      1024: {
          items: 3
      }
  }
```

**Comment by maxmarinich** [comment]
HI, @jaketrimble! Please, provide a code sample.

**Comment by martinbagshaw** [comment]
I have noticed a similar issue to Jake's, but not noticed any effect with or without the `responsive` prop included.

I run into this issue when using `onSlideChanged`, which I am using to reset a progress bar once the slide has changed. A small code sample:

```javascript
    <AliceCarousel
            autoPlay
            autoPlayInterval={slider.interval}
            buttonsDisabled
            dotsDisabled
            duration={slider.transition}
            fadeOutAnimation={slider.fadeAnimation}
            items={items} // an array of jsx items
            onSlideChanged={() => setChange(!change)}
            stopAutoPlayOnHover={slider.pauseOnHover}
          />
```

**Comment by maxmarinich** [comment]
@martinbagshaw, where you from get the items? Provide the full code sample. I guess you set items from the render. And if it's so the behavior is expected.

**Comment by maxmarinich** [comment]
Closed as expired. Before create new issue, please check live [demo](https://maxmarinich.github.io/react-alice-carousel/static/#basic) and new version of library.
