### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by care4pet** [maxmarinich/react-alice-carousel#135]
Hi, thanks for work.

So, problems are:
When using `infinity={false}` still have cloned elements, which is not good.

When I have 4 items in config, but there are only two children, it fills screen with them, breaking style completely. 

Doesn't work with children.

Sorry to uninstall it, looks very promising.

**Comment by maxmarinich** [comment]
Hi, @care4pet! Thanks for the feedback. Your issue and new features were implemented in a new version of library. Live demo is [here](https://maxmarinich.github.io/react-alice-carousel/static/#basic).
