### ISSUE TITLE
Is it possible to slide from the first item to the fourth item when click the "next" arrow directly?

### ISSUE THREAD

**Issue by WangXBruc** [maxmarinich/react-alice-carousel#142]
![image](https://user-images.githubusercontent.com/26540270/97544578-cad3c680-1a04-11eb-9408-f5a84c73a837.png)

**Current situation:**
There are 9 items(such as [1, 2, 3, 4, 5, 6, 7, 8, 9]) in total. Each slider contains 3 ones. When I click the "next" arrow, it will only slide from the first one to the second one(from showing [1, 2, 3] to [2, 3, 4]).
**What I want:**
What I want is the container directly slides to the fourth one(from showing [1, 2, 3] to [4, 5, 6]) when click the arrow. Is that possible?
Or, how should I set the props to achieve this?
Thank you.

**Comment by maxmarinich** [comment]
Hi, @WangXBruc! The gallery hasn't default behavior for your case. But [here](https://github.com/maxmarinich/react-alice-carousel/tree/v1#example-for-slideprevslidenext-page) is an example how to implement it.
