### ISSUE TITLE
[QUESTION/FEATURE] How to keep track of current activeIndex ?

### ISSUE THREAD

**Issue by aurelien-robineau** [maxmarinich/react-alice-carousel#147]
Hi!
How can I know what is the current active index ? `onSlideChanged` does not tell me if it changed to the next or the previous slide, so I can't use it.
Is there any way I can do that ?

If not I would suggest that you add some `onSlideChangedToPrevious` and `onSlideChangedToNext` handlers, wich could be usefull in some other situations too.

**Comment by maxmarinich** [comment]
Hi, @aurelien-robineau! You should combine `onSlideChange` && `onSlideChanged` methods.

* onSlideChange: Function - Fired while the event object is changing, before `onSlideChanged` will be triggered.
* onSlideChanged: Function - Fired after the event object was changed.

 Steps:
1. `setState({ activeIndex: 0 })`
2. click on the next button
3. `onSlideChanged` fired (activeIndex equal 1)
4. compare indexes from the `state` && `onSlideChanged`, detect if it changed to the next or the previous slide
5. update activeIndex in the `state` for the next action

```js
import React, { useState } from 'react';
import AliceCarousel from 'react-alice-carousel';
import 'react-alice-carousel/lib/alice-carousel.css';

const items = [
	<p className="yours-custom-class">1</p>,
	<p className="yours-custom-class">2</p>,
	<p className="yours-custom-class">3</p>,
];

const compare = (prev, curr) => {
	if (prev < curr) return 'next';
	if (curr < prev) return 'prev';
};

export function Gallery() {
	const [activeIndex, setActiveIndex] = useState(0);

	const onSlideChanged = ({ item }) => {
		console.log(`Status: ${compare(activeIndex, item)}`);
		setActiveIndex(item);
	};

	return <AliceCarousel mouseTracking items={items} onSlideChanged={onSlideChanged} />;
}

```

**Comment by aurelien-robineau** [comment]
Great! I did not know `onSlideChanged` gave the new item index back.
Thank you.
