### ISSUE TITLE
onClick custom button slide element

### ISSUE THREAD

**Issue by uendar** [maxmarinich/react-alice-carousel#149]
I have created 2 buttons one left one right. I want that when i click right to go to next slide and when i click left to go to previows element. 

What i have done is crated a method on click and when i click it i setIndex to a number but it wont work.

Any idea how to do it ?

**Comment by maxmarinich** [comment]
Hi, @uendar! Please, see [example (API)](https://maxmarinich.github.io/react-alice-carousel/static/#custom-components).
