### ISSUE TITLE
Items overflow when padding is set

### ISSUE THREAD

**Issue by jugurthakcm** [maxmarinich/react-alice-carousel#150]
When I set values to paddingLeft and paddingRight, items that aren't supposed to be showed until I click _next_ or _prev_ are showing up a little on the right and left of the carousel.

**Comment by jugurthakcm** [comment]
![Screenshot from 2020-11-19 11-47-10](https://user-images.githubusercontent.com/49955338/99656358-0fc7a780-2a5d-11eb-9348-633594dfd84e.png)

**Comment by jugurthakcm** [comment]
I fixed it by adding margin to **.alice-carousel > div:first-of-typel**

**Comment by maxmarinich** [comment]
Hi, @jugurthakcm! Please, see base [example](https://maxmarinich.github.io/react-alice-carousel/static/#stage-padding).
