### ISSUE TITLE
Trouble with autoheight

### ISSUE THREAD

**Issue by matheus-rosin** [maxmarinich/react-alice-carousel#151]
Hi!

When using `autoheight: true`, at the loading of the page, the first item does not show up correctly. The bottom of content is cut out. My carousel shows some image and texts, so I suppose that the carousel component sets the height before the content of the first item has been loaded.

Is there something I can do to trigger the height setting again?

Thanks!

**Comment by maxmarinich** [comment]
Hi, @matheus-rosin! Please, provide the code sample.

**Comment by maxmarinich** [comment]
Please, see [example](https://maxmarinich.github.io/react-alice-carousel/static/#auto-height). Closed like not relevant.

**Comment by martdavidson** [comment]
@matheus-rosin https://github.com/maxmarinich/react-alice-carousel/issues/156 solved this exact issue for me.

**Comment by emanuallan** [comment]
I am seeing this issue now, will post when I find a solution.
