### ISSUE TITLE
Prevent container scrolling while carousel is changing

### ISSUE THREAD

**Issue by ledbetterljoshua** [maxmarinich/react-alice-carousel#152]
When using the carousel on mobile, I am capable of dragging left or right to update the carousel and then drag up or down, which scrolls the page / container. 

Ideally, the drag event on the carousel would cancel out any drag events and scrolling of the parent. Is there any way to accomplish this?

**Comment by maxmarinich** [comment]
Hi, @ledbetterljoshua! Set `touchMoveDefaultEvents` to `false`, like so:
```js
import React from 'react';
import AliceCarousel from 'react-alice-carousel';
import 'react-alice-carousel/lib/alice-carousel.css';

const items = [
    <div className="item" data-value="1">1</div>,
    <div className="item" data-value="2">2</div>,
    <div className="item" data-value="3">3</div>,
    <div className="item" data-value="4">4</div>,
    <div className="item" data-value="5">5</div>,
];

const Carousel = () => (
    <AliceCarousel
        mouseTracking
        items={items}
        touchMoveDefaultEvents={false}
    />
);
```

**Comment by ledbetterljoshua** [comment]
That's perfect. I just totally missed that in the readme. Thanks, @maxmarinich!

**Comment by ledbetterljoshua** [comment]
Oh. I see why this is not set by default: it literally prevents scrolling the parent. Ideally, this would prevent scrolling of the parent only while the carousel is being scrolled.

**Comment by phones24** [comment]
Any updates on this? I have vertically scrollable containers inside carousel and I can drag the content inside container up and down while scrolling the carousel horizontally. As @ledbetterljoshua suggest it would be cool to have the flag that tells carousel to prevent vertical scrolling while being swiped horizontally.

**Comment by zeabdelkhalek** [comment]
@phones24 @ledbetterljoshua any workaround for resolving the issue?

**Comment by phones24** [comment]
@zeabdelkhalek the workaround is changing the library unfortunately (
