### ISSUE TITLE
Next Previous button in side

### ISSUE THREAD

**Issue by codewithvk** [maxmarinich/react-alice-carousel#158]
How can i create next and prev button like this?
![image](https://user-images.githubusercontent.com/61119120/103189322-25e54500-48f2-11eb-8b60-08a0a97e6ff6.png)
ps: For dekstop

**Comment by maxmarinich** [comment]
Hi, @codewithvk! First you should read the docs([example](https://maxmarinich.github.io/react-alice-carousel/static/#custom-components)).
