### ISSUE TITLE
Triggering slideNext/slidePrev from custom components

### ISSUE THREAD

**Issue by 6ichem** [maxmarinich/react-alice-carousel#159]
I'm trying to trigger the carousel to slide using a custom button (onclick event). not sure if it's possible using this library but I couldn't figure out how to use the methods on the docs so I would like a code example if possible. Thanks

**Comment by 6ichem** [comment]
Figured it out through [this](https://github.com/maxmarinich/react-alice-carousel/issues/115)

**Comment by maxmarinich** [comment]
Hi, @6ichem! First read the [docs](https://github.com/maxmarinich/react-alice-carousel#react-alice-carousel) (needed [example](https://maxmarinich.github.io/react-alice-carousel/static/#custom-components)).
