### ISSUE TITLE
Desktop swiping with link cards does not prevent links from being clicked

### ISSUE THREAD

**Issue by drmanitoba** [maxmarinich/react-alice-carousel#16]
Hi, me again, I'm having an issue right now where I've got a carousel full of cards that are also links. We're noting an issue where when we do drag-scrolling on desktop, the carousel doesn't trap that click event and stop propagation, so the click travels through to the card and after swiping is done, it causes navigation to happen.

Are there hooks I can access via the API to prevent this from happening or does this require a change to the library? I'm happy to open a PR if need be, just wanted to get feedback before diving in.

**Comment by maxmarinich** [comment]
Hi @drmanitoba! Looks like this is an expected behavior. Please provide a code sample, so I can make sure of that.

**Comment by maxmarinich** [comment]
Hi @drmanitoba! Like i've noticed above, this is an expected behavior. To avoid that you should handle drag event independently something like this: 

```
import { Link } from 'react-router-dom'

function SomeLink() {
  const handleOnDragStart = (e) => e.preventDefault()

  return (
    <Link to='#' onDragStart={handleOnDragStart} >Some text</Link>
  )
}
```
