### ISSUE TITLE
Render multiple carousel on one page cause error

### ISSUE THREAD

**Issue by kappaxbeta** [maxmarinich/react-alice-carousel#165]
Hello folk,

the carousel is awesome, it works out of the box without jquery props for that.

I just saw when u Render two carousel, react will throw a error, becuase the render Item are wrapped where the 
key is always the same for diffrent instances.

in the file: 
react-alice-carousel/src/lib/react-alice-carousel.tsx 
and the function _renderStageItem, it would be helpful, if it would be possible to give the carousel a uniqe pre or suffix.

Cheers,
Jens

**Comment by maxmarinich** [comment]
Hi, @kappaxbeta! Please, provide the code sample or error log.

**Comment by kappaxbeta** [comment]
Sure,

you just get this error in develop
<img width="780" alt="Screenshot 2021-01-16 at 14 50 42" src="https://user-images.githubusercontent.com/7612464/104813596-69084900-580a-11eb-8b34-3800cb503269.png">

I took the screenshot on the page you reference, as you can see they use the same key in the loop for the slide stage-item-${index} 
<img width="405" alt="Screenshot 2021-01-16 at 14 48 38" src="https://user-images.githubusercontent.com/7612464/104813597-6c033980-580a-11eb-9f5b-f87a30e39797.png">

**Comment by maxmarinich** [comment]
@kappaxbeta, could you provide a code sample?

**Comment by maxmarinich** [comment]
Closed as irrelevant. Live demo for inspecting is [here](https://maxmarinich.github.io/react-alice-carousel/#custom-components).
