### ISSUE TITLE
Question: How to build project?

### ISSUE THREAD

**Issue by drmanitoba** [maxmarinich/react-alice-carousel#17]
Hi, I'm being super chatty, but this is just a quick question:

How do I build the project, like, if I wanted to symlink it into my own project?

I understand how I can run it locally, but I can't find anything that builds it to its final dist output.

**Comment by maxmarinich** [comment]
Hi @drmanitoba , you're right! The project has no any build tools. It looks strange, but to create bundle you should use third-party build tools.
