### ISSUE TITLE
How to get the right values on the first render from isNextSlideDisabled and isPrevSlideDisabled?

### ISSUE THREAD

**Issue by daltonmenezes** [maxmarinich/react-alice-carousel#170]
First, thanks for this lib.

I'm trying to get the right values on the first render from **isNextSlideDisabled** and **isPrevSlideDisabled** properties to set the disabled behavior correctly on my custom controllers.

I was trying to get the values from **onInitialized**, but as you can see on the _console log_ on the screenshot, the **isNextSlideDisabled** was **false** instead of **true** as the default controllers on the bottom of the screenshot. How can I solve it?

![img](https://i.imgur.com/nSAmskb.png)

**Comment by maxmarinich** [comment]
Hi, @daltonmenezes! Please, provide a code sample.

**Comment by daltonmenezes** [comment]
@maxmarinich I found the problem on my code. **Children.toArray()** was empty at first, so I did a conditional rendering to not render the carousel until the Children array was filled, that was the solution for me, it wasn't a problem related to your lib, I'm sorry about that.
