### ISSUE TITLE
activeIndex defaults back to 0

### ISSUE THREAD

**Issue by kylesierens** [maxmarinich/react-alice-carousel#173]
I'm trying to get the gallery to not shift back to ZERO index, hard left aligned.
If I don't set activeIndex or set it as null, and have autoWidth items (multiple items in the viewport), If I select an item thats outside of the initial "slide" it jumps back to zero index. I don't want the selected item to always be hard left aligned.

It would be nice if the selected item was still within viewport it wouldn't shift the scrollable container at all.

**Comment by maxmarinich** [comment]
Hi, @kylesierens.Please update to v2.4, see [auto-width](https://maxmarinich.github.io/react-alice-carousel/#auto-width) and updated [custom-components](https://maxmarinich.github.io/react-alice-carousel/#custom-components) examples.  If it not resolve your issue, provide a code sample.

**Comment by kylesierens** [comment]
Wonderful!! Thank you!

**Comment by kylesierens** [comment]
Unfortunately this doesn't quite do what I had hoped it would. Your thumbs aren't swip-able, and if set to infinite they would always left align.  One way I could see it working with the example you provided, would be the pass a custom renderPrevButton and renderNextButton. Thats the action I'd like to trigger, not just +- the index for activeIndex, but to move the entire slide (group of 4) at once.

Or perhaps I'm missing something entirely in the documentation. I'm not sure how to use these methods, but they might also be what I'm seeking: 
Methods
slidePrev(e: Event) => void : Go to the prev slide.
slideNext(e: Event) => void : Go to the next slide.
slideTo(activeIndex?: number) => void : Go to the specified slide.

Thanks.
