### ISSUE TITLE
Infinite loop, is not a loop, but a back to square one.

### ISSUE THREAD

**Issue by kylesierens** [maxmarinich/react-alice-carousel#174]
Can you make infinite loop and actual loop when using autoWidth?

Right now it animates in reverse back to array[0] very poor UX.

**Comment by maxmarinich** [comment]
Hi, @kylesierens. Please  look [example](https://maxmarinich.github.io/react-alice-carousel/#auto-width). And if it not resolve your issue, provide a code sample.

**Comment by kylesierens** [comment]
Yes, that seems to work, I've narrowed it down to the onClick of the element/item. Im my code I have within an onClick() and this causes it to jump backwards to the closest array pos.
`items.map(item,i)=>{
    <Item
        key={i}
        **onClick={() => setCurrentSlide(i)}**>
    {item.label}
    </Item>
})`

Hope that helps

**Comment by maxmarinich** [comment]
Problem is in your code. You every time passing new props and the gallery restarts. Save `responsive` property in state.

**Comment by kylesierens** [comment]
Wonderful!! Thank you!

**Comment by jgbharris** [comment]
Hi I'm still getting this issue, the carousel goes through two and a half cycles and then shifts back to array[0]
