### ISSUE TITLE
Free mode?

### ISSUE THREAD

**Issue by dartess** [maxmarinich/react-alice-carousel#176]
react-alice-carousel support free mode? eg https://swiperjs.com/demos/150-freemode.html

**Comment by maxmarinich** [comment]
Hi, @dartess! Support with a small difference. Please see [autoWidth](https://maxmarinich.github.io/react-alice-carousel/#auto-width) example.

**Comment by dartess** [comment]
Unfortunately, this is NOT free mode. Slides stick in a specific position when released.

It would be cool to have a completely free mode.
