### ISSUE TITLE
Keys control

### ISSUE THREAD

**Issue by Ramanpreet6262** [maxmarinich/react-alice-carousel#177]
How can I make the slides change by pressing the left and right keys of the keyboard?

I tried using v1 of this library for keyboard control but their `slideToIndex` prop is not working...

Can anyone help me with either keys control in v2 or slideToIndex issue in v1

**Comment by maxmarinich** [comment]
Hi, @Ramanpreet6262! Starting from v2, use the [slideTo](https://github.com/maxmarinich/react-alice-carousel#methods) method. See live [demo](https://maxmarinich.github.io/react-alice-carousel/#custom-components-refs). The v2 has't got keyboard events, you should add them additionally e.g.:
```js
  componentDidMount() {
    window.addEventListener('keyup',   function handleOnKeyUp(e) {
      switch (e.code) {
        case 'Space':
        // call handler
        case 'ArrowLeft':
        // call handler
        case 'ArrowRight':
        // call handler 
      }
    })
  }
```
