### ISSUE TITLE
Suppress item click event on drag

### ISSUE THREAD

**Issue by mecha** [maxmarinich/react-alice-carousel#178]
When using `mouseTracking` and `touchTracking`, dragging the items in the carousel causes the item that is "tracked" by the mouse or touch event to have its click event handler fire once the tracking is finished.

I've set up a [CodeSandbox](https://codesandbox.io/s/alice-carousel-item-click-event-bjy94?file=/src/App.js) for demonstration. Try dragging the items in the carousel with the mouse to reproduce.

This may be a question that is unrelated to AliceCarousel - if so, I apologize. But otherwise, is there a way to prevent this?

**Comment by maxmarinich** [comment]
Hi, @mecha! This behavior is an expected. The JS events are working so. The algorithm Drag’n’Drop includes: `mousedown, mousemove, mouseup` events. The `click` is a complex event, includes: `mousedown, mouseup`. For elegant behavior, use the `touchmove` event instead of `mousedrag` when you need to further process a `click`. And if you need to handle both "mousedrag" and "click" events, you should handle them independently.

**Comment by oldo** [comment]
Hi @maxmarinich 
I'm having difficulty figuring this out. Are you able to point me to any examples of this successfully configured?

**Comment by maxmarinich** [comment]
Hi, @oldo ! Please see [#Base](https://maxmarinich.github.io/react-alice-carousel/#custom-components) or [#Props](https://maxmarinich.github.io/react-alice-carousel/#custom-components-props) examples.

**Comment by maxmarinich** [comment]
```js
import React, { useState } from 'react';
import AliceCarousel from 'react-alice-carousel';
import 'react-alice-carousel/lib/alice-carousel.css';

const responsive = {
    0: { items: 3},
};

const createItems = (length, [handleClick]) => {
    let deltaX = 0;
    let difference = 0;
    const swipeDelta = 20;

    return Array.from({ length }).map((item, i) => (
        <div
            onMouseDown={(e) => (deltaX = e.pageX)}
            onMouseUp={(e) => (difference = Math.abs(e.pageX - deltaX))}
            onClick={() => (difference < swipeDelta) && handleClick(i)}
        />
    ));
};

const Carousel = () => {
    const [activeIndex, setActiveIndex] = useState(0);
    const [items] = useState(createItems(5, [setActiveIndex]));
    const syncActiveIndex = ({ item }) => setActiveIndex(item);

    return 
        <AliceCarousel
            mouseTracking
            items={items}
            activeIndex={activeIndex}
            responsive={responsive}
            onSlideChanged={syncActiveIndex}
        />
};
```

**Comment by oldo** [comment]
Thanks so much @maxmarinich 
Super helpful. The above worked perfectly for me :-)

**Comment by janglewood** [comment]
anyone who will use this example you should use memo for items, because this approach `const [items] = useState(createItems(5, [setActiveIndex]));` will recreate items on every render and `const items = useMemo(() => createItems(5, [setActiveIndex]), []);` will create once
