### ISSUE TITLE
Can't change styling for a specific Carousel

### ISSUE THREAD

**Issue by Atif252** [maxmarinich/react-alice-carousel#180]
I am using multiple Carousels across the application and I want to style them separately instead of applying global styles.

**Comment by maxmarinich** [comment]
Hi, @Atif252! Only two ways: 
- wrap every instance by custom element with classname, manage it using global styles
- use custom components for controls
Hope live [demo](https://maxmarinich.github.io/react-alice-carousel/#custom-components) will help you.
