### ISSUE TITLE
Prop warning on ssr classname after update.

### ISSUE THREAD

**Issue by chuckstock** [maxmarinich/react-alice-carousel#183]
![Screen Shot 2021-03-17 at 3 58 21 PM](https://user-images.githubusercontent.com/9020007/111544110-9bb2bd00-8739-11eb-9670-ae952445478f.png)

Getting this warning after updating to version 2.4 using nextjs.

**Comment by maxmarinich** [comment]
Hi, @chuckstock! These is an expected behavior. This is a mechanism how(why) detect [csr/ssr](https://github.com/maxmarinich/react-alice-carousel/issues/167).  But you're right, it might be more elegant. In the next version the lib become new prop for enabling this functionality if necessary only.

**Comment by shirazz** [comment]
hello @maxmarinich would you mind sharing some inputs here on what can be done to fix this.

**Comment by maxmarinich** [comment]
Added in #188 v2.5.1. To enable css modifier set `ssrSilentMode` to `true`.

**Comment by adrienharnay** [comment]
Hello, just tested with v2.5.1 and still have this error:
<img width="1038" alt="Screenshot 2021-04-16 at 17 50 03" src="https://user-images.githubusercontent.com/15089053/115051106-bf098d00-9edc-11eb-8de5-663cb33159ae.png">

**Comment by maxmarinich** [comment]
i guess you use `responsive` property, if some item is more than 1 - there is expected
```js
const responsive = {
  0: { items: 1 },
  568: { items: 2 },
  1024: { items: 3 },
}
```
try removing the `responsive` property, the warning should disappear
or read about `innerWidth` property, it can help resolve the case
