### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by GoodGuyMarco** [maxmarinich/react-alice-carousel#184]
Hey guys, is keyboard navigation intended to be supported any time soon?

**Comment by maxmarinich** [comment]
Hi, @GoodGuyMarco! Will be added in the next versions.

**Comment by maxmarinich** [comment]
@here Added in #188. Upd to v2.5.1. Demo https://maxmarinich.github.io/react-alice-carousel/#events.

**Comment by GoodGuyMarco** [comment]
Lovely, thanks a lot ❤️
