### ISSUE TITLE
onSlideChange event not firing immediately upon drag

### ISSUE THREAD

**Issue by oldo** [maxmarinich/react-alice-carousel#187]
Hi there, I am using the `onSlideChange` event and finding that when I start dragging with my mouse on desktop the event is not fired unless I drag the mouse completely off the carousel. I would like it to fire immediately when the drag event starts. This was previously working as expected, has anything changed with a recent update?

Thanks.

**Comment by maxmarinich** [comment]
Hi, @oldo! Fixed #188. Upd to v2.5.1. Demo https://maxmarinich.github.io/react-alice-carousel/#events.

**Comment by oldo** [comment]
Great, thanks @maxmarinich !
