### ISSUE TITLE
Disable touchmove on page scroll

### ISSUE THREAD

**Issue by francesco-albanese** [maxmarinich/react-alice-carousel#19]
As per title I couldn't find a way to prevent the slider from swiping when scrolling the page.
I tried using CSS3 property `touch-action: pan-y` but it's not making any difference. The issue is pretty annoying especially on mobile devices, when you scroll down the page and your finger is on top of the slider, it starts moving and makes the interaction confusing.
Any idea on how to solve the issue?
Thanks

**Comment by maxmarinich** [comment]
fixed in [3a298a0](https://github.com/maxmarinich/react-alice-carousel/commit/3a298a0af40d87a8b36748a8ceee21c30463c847)

**Comment by arslansajid** [comment]
I am facing the same issue.
"react-alice-carousel": "^1.16.0",
