### ISSUE TITLE
Issues with 100% height display for cloned items

### ISSUE THREAD

**Issue by Lateralus-lab** [maxmarinich/react-alice-carousel#195]
If I turn on infinite mode for a slider, it creates cloned items in "li" elements. 

The problem is that cloned items aren't 100% height. The original cards are displaying correctly, but cloned ones aren't. 

Does anyone know how to solve this issue? I was playing with CSS for a bit with no luck. 
[
![carusel-issues](https://user-images.githubusercontent.com/59764339/117581590-7fa61900-b0f5-11eb-803f-dec47e2344c0.png)
](url)

**Comment by maxmarinich** [comment]
Hi, @Lateralus-lab. Please provide a code sample.

**Comment by Lateralus-lab** [comment]
I'm sorry, but I switched to
