### ISSUE TITLE
Smoother animations when using AnimationType "slide"

### ISSUE THREAD

**Issue by Vadorequest** [maxmarinich/react-alice-carousel#198]
Is it possible to configure a "smoother" animation when using the `AnimationType={'slide'}` mode?

I'd like the slide to slow down when arriving at the destination, it's a bit "too raw" by default.

**Comment by maxmarinich** [comment]
Hi, @Vadorequest! Use `animationEasingFunction` property.

**Comment by Vadorequest** [comment]
Thanks, I had missed it. https://developer.mozilla.org/ru/docs/Web/CSS/animation-timing-function
