### ISSUE TITLE
Rendering less items than the configured number of items for the current resolution

### ISSUE THREAD

**Issue by cguedes** [maxmarinich/react-alice-carousel#20]
Hi,

I'm using you lib with success so far. Thanks for your job here. 🎉 

I'm using the lib to display a carousel of products. I have configured some values for responsive widths. 

Everything is OK if the number of products is equals or greater than that number. But when the number of items is less, then I have an **issue by having the items resized**.

Can we have an option to add "transparent/fake" items in order to maintain the width?
Ideally they should be centered (ideally the alignment should be configured).

Another option would be to have an optional property for the **maximum width for items**.

**Comment by maxmarinich** [comment]
@cguedes, hi! Please provide the code sample.

**Comment by cguedes** [comment]
@maxmarinich Check the following codesandbox sample.

* Example: https://pyly505oqm.codesandbox.io/
* Sandbox: https://codesandbox.io/s/pyly505oqm 

I was able to "almost" achieve my goal by using flex in my components inside the carousel.

**Comment by maxmarinich** [comment]
Hi, @cguedes! The carousel behaves as expected. User should keep the data up to date. You've created the degenerated situation and broken the logic, e.g. the case when the number of gallery items became less than in `responsive` config.
