### ISSUE TITLE
Set height of all slides to the height of the tallest one

### ISSUE THREAD

**Issue by AntonioRedondo** [maxmarinich/react-alice-carousel#203]
Hi @maxmarinich,

Thanks for this great React library.

I was wondering if there is some way to set the height of all cards to the height of the tallest one? With the CSS `flex` rule this task is trivial. But since the slides are wrapped in
```html
<ul class="alice-carousel__stage">
  <li class="alice-carousel__stage-item"><div>Slide 1</div></li>
  <li class="alice-carousel__stage-item"><div>Slide 2. This is the tallest slide.</div></li>
  <li class="alice-carousel__stage-item"><div>Slide 3</div></li>
</ul>
```
the task turns complicated.

I've tried to set `alice-carousel__stage` class to `display: flex`. But as soon as I do this the layout of the `alice-carousel__stage` breaks and then all slides get a very small width. This width is set by JavaScript as far as I understand. So I cannot overrule it with CSS, not even with `!important`.

I've been playing with CSS on the different classes. But I've been unable to get all slides to expand to the tallest one without having to resort to harcode a fix height. Which is not what I want to do.

**Comment by maxmarinich** [comment]
Hi, @AntonioRedondo! Please provide a graphic sample what you need. Possible the issue related with #197

**Comment by maxmarinich** [comment]
You can resolve the issue with next:
```css
.alice-carousel__stage {
  display: flex
}
.alice-carousel__stage-item {
  flex: 1 0 auto;
  height: auto;
}
.item {
  background: #ccc;
  height: 100%;
}
```
```js
import React from "react";
import AliceCarousel from "react-alice-carousel";
import "react-alice-carousel/lib/alice-carousel.css";

const responsive = {
  0: { items: 3 }
};

const items = [
  <div className="item" >1</div>,
  <div className="item" >2<div>3</div></div>,
  <div className="item" >3</div>,
];

function () {
  return <AliceCarousel items={items} responsive={responsive} />;
}
```
Before:
<img width="555" alt="ib" src="https://user-images.githubusercontent.com/9882979/124236366-0936fd80-db1f-11eb-96d8-cc695dacb36d.png">
After:
<img width="551" alt="flex" src="https://user-images.githubusercontent.com/9882979/124236411-148a2900-db1f-11eb-88e4-4c3e9a6caf49.png">

**Comment by AntonioRedondo** [comment]
Fantastic! That worked! Thanks for the quick response!

**Comment by najibullo-kenjaev** [comment]
@AntonioRedondo  where to put these css classes 
.alice-carousel__stage {
  display: flex
}
.alice-carousel__stage-item {
  flex: 1 0 auto;
  height: auto;
}
.item {
  background: #ccc;
  height: 100%;
}
