### ISSUE TITLE
Accesible controls?

### ISSUE THREAD

**Issue by devmxv** [maxmarinich/react-alice-carousel#209]
Hello,
Not an issue, but a question/suggestion:
Is it possible that the play/pause button could be accesible? I am using this carousel (great work BTW) for a website that requires accesibility features and I do not know how to achieve that with the current release.

**Comment by maxmarinich** [comment]
Hi, @devmxv! Please use `autoPlayControls` property like [this](https://maxmarinich.github.io/react-alice-carousel/#auto-play).
