### ISSUE TITLE
All widths set to 0 on initial render with NextJS (v9.2)

### ISSUE THREAD

**Issue by alexrdz** [maxmarinich/react-alice-carousel#210]
I am using the carousel on a NextJS app. It works perfectly except for initial the render. 
On initial render, all items in the carousel and the carousel itself (`.alice-carousel__stage` and all subsequent `alice-carousel__stage-item`) have a width of `0`. On resize everything is normal and works well. 

I have buttons and controls disabled and using `responsive` object to set custom breakpoints. 

Is there some specific setting I am missing? Has anyone else experienced this behavior? 

Using:
NextJS `v.9.2.0`
React Alice Carousel `v.2.5.1`

Thanks!

**Comment by maxmarinich** [comment]
Hi, @alexrdz! This is an expected behavior. Because there are no client events on the server side. You can use the `innerWidth` property to specify a static screen value on the server, e.g.: 
```js
import React from 'react';
import AliceCarousel from 'react-alice-carousel';
import 'react-alice-carousel/lib/alice-carousel.css';

const Gallery = () => {
  const getInnerWidth = () => {
    try {
      // if client
      return window.innerWidth;
    } catch() {
    // if server, set any desired value
      return 1024;
    }   
  };

  return (
    <AliceCarousel items={[]} innerWidth={getInnerWidth()} />
  );
}
```

**Comment by alexrdz** [comment]
Thank you, @maxmarinich! Much appreciated!
