### ISSUE TITLE
Alice carousel is having a conflict with it's own properties

### ISSUE THREAD

**Issue by debleena2707** [maxmarinich/react-alice-carousel#215]
This is my code:
`<Box className="slider-container" style={{position: 'fixed',bottom: 0}}>
                    <AliceCarousel autoPlay autoPlayInterval="2000" autoHeight autoWidth disableDotsControls infinite>
                        <img alt="sliderImage" src={image1} className="sliderimg" role="presentation"/>
                        <img alt="sliderImage" src={image2} className="sliderimg" role="presentation"/>
                        <img alt="sliderImage" src={image3} className="sliderimg" role="presentation"/>
                        <img alt="sliderImage" src={image4} className="sliderimg" role="presentation"/>
                        <img alt="sliderImage" src={image5} className="sliderimg" role="presentation"/>
                        <img alt="sliderImage" src={image6} className="sliderimg" role="presentation"/>
                        <img alt="sliderImage" src={image7} className="sliderimg" role="presentation"/>
                        <img alt="sliderImage" src={image8} className="sliderimg" role="presentation"/>
                        <img alt="sliderImage" src={image9} className="sliderimg" role="presentation"/>
                    </AliceCarousel>
                </Box>`
However, when the browser is refreshed the carousel does not appear, but do nothing and hit save, i.e. when react re-renders: the carousel appears.

**Comment by maxmarinich** [comment]
Hi, @debleena2707! I guess this issue is strongly dependent code in the `render` of wrapper element. And the carousel cannot calculate values because when it does, the height / width of the parent is roughly 0. You can use `renderKey` property like in [this](https://github.com/maxmarinich/react-alice-carousel/issues/182) issue.  Or do ths:

```js
import React, { useState, useEffect } from 'react';

function App() {
      const [renderKey, setKey] = useState(0);
      
      useEffect(() => {
          setKey(Date.now());
      }, []);
      
      <AliceCarousel
          renderKey={renderKey}
          items={[
            <img src={zeroSrc} alt="0" className="img-thumbnail" />,
            <img src={oneSrc} alt="1" className="img-thumbnail" />,
            <img src={twoSrc} alt="2" className="img-thumbnail" />,
            <img src={threeSrc} alt="3" className="img-thumbnail" />,
          ]}
      />

```
