### ISSUE TITLE
Hide Controls?

### ISSUE THREAD

**Issue by sethwms** [maxmarinich/react-alice-carousel#216]
I didn't see a way to simply hide the control bar with the given options.

Am I missing something, or could this be added?

Great tool!  Thanks!

**Comment by maxmarinich** [comment]
Hi, @sethwms! Accordingly [docs](https://github.com/maxmarinich/react-alice-carousel#options) use `disableButtonsControls` & `disableDotsControls `. Example: https://maxmarinich.github.io/react-alice-carousel/#custom-components-props

**Comment by sethwms** [comment]
My mistake. I had a typo in the control buttons setting that prevented it from being turned off.

Thanks for the quick response!
