### ISSUE TITLE
Stop auto slide after clicked item?

### ISSUE THREAD

**Issue by khanitnanj** [maxmarinich/react-alice-carousel#217]
when has 10 items the first 5 items will auto slide if I clicked item 2, 3, 4

Can I make it stop?

**Comment by maxmarinich** [comment]
Hi, @khanitnanj! Please provide a code sample and explain the issue.

**Comment by khanitnanj** [comment]
You can use this code 

https://maxmarinich.github.io/react-alice-carousel/#custom-components

I've try the first one 

In Thumbnail images if clicked on image number 2,  the slide shouldn't move. I would like to change the thumbnail slide manually.

**Comment by maxmarinich** [comment]
Yes you can. The [lib](https://github.com/maxmarinich/react-alice-carousel) has extensive capabilities and highly configurable properties. Please use last if the live samples not cover your issue.
