### ISSUE TITLE
React re-render (state change) resets slider

### ISSUE THREAD

**Issue by Airrudi** [maxmarinich/react-alice-carousel#218]
Hi,

I've got a specific usecase I can't get to work:

I basically use the carousel as a background image slider.
On top of this slider there is a text (text is not inside the slider items, since I don't want this text to slide with the items), this text needs to match the background image, so it needs to be updated whenever the slide changes.

E.g. slide 1 (image ship) --> Text is 'this is a ship'
E.g. slide 2 (image car) --> Text is 'this is a car'
E.g. slide 3 (image plane) --> Text is 'this is a plane'

I am now updating the text using a state update in the onSlideChange callback.

Simplified:
```
const [slide, setSlide] = useState(0)

const data = [
 {image: '', text: 'this is a ship'},
 {image: '', text: 'this is a car'},
 {image: '', text: 'this is a plane'}
]

const items = data.map(entry => <div background-image: entry.image />);

 const onSlideChange = (e) => {
        setSlide(e.slide);
    }

 <AliceCarousel 
                        slideToIndex={slide}                        
                        items={items}
                        onSlideChange={onSlideChange}
                    />

<p>items[slide].text</p>
```

Whenever the onSliderChange is triggered and the state is updated, it re-renders the page with slider etc. This causes the slider to go back to the first slide. Even using slideToIndex={slide} is not helping.

Thanks in advance

**Comment by maxmarinich** [comment]
Hi, @Airrudi! According [docs](https://github.com/maxmarinich/react-alice-carousel#options) from v2 you should use `activeIndex ` instead `slideToIndex`(from v1).
