### ISSUE TITLE
Incorrect typescript definition

### ISSUE THREAD

**Issue by jl-ib** [maxmarinich/react-alice-carousel#22]
In react-alice-carousel.d.ts

`items?: Array;`

Should be 

`items?: {}[];`
or
`items?: Array<{}>;`

Otherwise this error is raised:
`Generic type Array<T> requires 1 type arguments.`

**Comment by maxmarinich** [comment]
Hi, @jl-ib, Thanks! Fixed in [ac0afc](https://github.com/maxmarinich/react-alice-carousel/commit/ac0afc1d55d4bc2ed1b21648aa6fa83ffb6b2227).
