### ISSUE TITLE
current Active Index

### ISSUE THREAD

**Issue by Anan7Codes** [maxmarinich/react-alice-carousel#222]
Hey, is there a way to get the current index position? Basically I'm looking to add an opacity on my left arrow when the index is at 0 and right arrow when the index is my array's length.

**Comment by maxmarinich** [comment]
Hi, @Anan7Codes! For your case i'd use `isPrevSlideDisabled` or `isNextSlideDisabled` from callback like [here](https://maxmarinich.github.io/react-alice-carousel/#events).
