### ISSUE TITLE
how to Add gap between items card

### ISSUE THREAD

**Issue by Bawanthathilan** [maxmarinich/react-alice-carousel#227]
![image](https://user-images.githubusercontent.com/38850236/159834417-a1f5b53c-804b-47b1-8305-0a5899cf62f2.png)

**Comment by maxmarinich** [comment]
Hi, @Bawanthathilan! See code [samples](https://maxmarinich.github.io/react-alice-carousel/) , use common css.

<img width="1346" alt="Снимок экрана 2022-03-25 в 16 22 35" src="https://user-images.githubusercontent.com/9882979/160128995-00bcd415-c72a-4b9f-b44b-2d5e9752a33a.png">
