### ISSUE TITLE
animationType="fadeout"  doesnt work with autoHeight 

### ISSUE THREAD

**Issue by kno-raziel** [maxmarinich/react-alice-carousel#229]
I'm using this configuration and the fadeout doesnt work

```tsx
 <AliceCarousel
    animationType="fadeout"
    animationDuration={800}
    disableButtonsControls
    infinite
    mouseTracking
    autoHeight
    items={items}
    ref={carouselRef}
  />
 ```
 
 If i remove the autoHeight it works.

**Comment by maxmarinich** [comment]
Hi, @kno-raziel! This was done on purpose to make the animation more elegant. But if you opened this topic, then someone needs such functionality. Will added in the next release.

**Comment by maxmarinich** [comment]
Applied at v.2.6.0
