### ISSUE TITLE
Make 'responsive' accept all options instead of just 'items'

### ISSUE THREAD

**Issue by tedlin182** [maxmarinich/react-alice-carousel#23]
It would be great to allow you to customize all of the options at every breakpoint. I sometimes want to hide the toggles and only show the dots on mobile and vice versa.

Just a thought. Thanks!

**Comment by maxmarinich** [comment]
Hi, @tedlin18! Please, describe real case. All props is dynamically.

**Comment by tedlin182** [comment]
Hey @maxmarinich !

Sorry I was out of town last week and just saw this.

Basically my use case was to be able to set other options in addition to `items` under the `responsive` prop. 

eg. I was trying to do something like this, but only the `items` option picked up at the different breakpoints. Hope this makes sense!

```
<AliceCarousel
  responsive={{
    480: { 
       items: 2,
       buttonsDisabled: false,
       playButtonEnabled: true,
    },
    1024: {
       items: 4,
       buttonsDisabled: true,
       playButtonEnabled: false,
    }
  }}
>
....
</AliceCarousel>

```

**Comment by maxmarinich** [comment]
Hi, @tedlin182! Your decision violates the principle of responsibility.
To resolve the case you can use next:
1. set props to the `state`
```
state = {
  buttonsDisabled: false,
  playButtonEnabled: true,
}
```
2. add resize listener
```
  componentDidMount() {
    window.addEventListener('resize', this._windowResizeHandler)
  }
  componentWillUnmount() {
    window.removeEventListener('resize', this._windowResizeHandler)
}
```
3. describe logic
```
_windowResizeHandler () {
  // primitive example
  if (window.innerWidth > 480) {
    this.setState({
      buttonsDisabled: true,
      playButtonEnabled: false,
    }) 
  }
}
```
4. 
```
<AliceCarousel
  buttonsDisabled={this.state.buttonsDisabled}
  playButtonEnabled={this.state.playButtonEnabled}
  {...otherProps}
/>
```

**Comment by tedlin182** [comment]
@maxmarinich

Awesome, thanks for explanation and the reference to the concept! 

It totally makes sense so thanks for the reply!

**Comment by tiggeymone** [comment]
@maxmarinich , why this feature will violate the principle of responsability? Or better: if this feature will violate the pof, doesn't the prop "responsive: items" violates it too? I just managed to create my own resize events and everything works, but this point isn't still clear for me. For instance, other carousels, like react-slick, implements the responsive feature this way, and I think that it should be very convenient to have it built in instead of managing it with hooks.

Thank you in advance for your patience
