### ISSUE TITLE
Centering a target inside the carousel

### ISSUE THREAD

**Issue by NoHop3** [maxmarinich/react-alice-carousel#232]
Hello! Did not know how to reach more efficiently so I would write here. Hope you would help me out as a creator of this awesome carousel library.

In short - I am building a fullstack project, I am fetching some product data from my backend and presenting it in a responsive way. All good on a phone device - having only 1 item at a time. 
![image](https://user-images.githubusercontent.com/82092907/163628708-fab379a1-11a6-4a28-aa2e-4d643a0f40d1.png)

However - this is what I end up with on a tablet or laptop
![image](https://user-images.githubusercontent.com/82092907/163628535-dc5544fa-4938-478a-bed2-1a7d7c453947.png)
![image](https://user-images.githubusercontent.com/82092907/163628571-655acf15-d7a2-457f-84ea-b196501233ca.png)

To further explain taking in consideration the last image I want the targetImage which is the one with opacity:1 to be at position 3 (in the center of the carousel)

I am helpless to order them accordingly. I am correctly moving the target accross my items like so:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/82092907/163629857-8924ab56-54c3-40bf-834f-9863c1990d54.gif)

Sliding is moving forward/backkwards and changing my name/price properties but I cannot make the target centered. I am clueless. 

This is what I am using so far
![image](https://user-images.githubusercontent.com/82092907/163628872-c8464258-3315-48c5-ab71-5590201636ec.png)
![image](https://user-images.githubusercontent.com/82092907/163628894-8f3de3d1-3ab5-43bf-8157-04e64247a0d4.png)

### EDIT: Posted a question on [StackOverFlow](https://stackoverflow.com/questions/71889810/creating-a-centered-carousel-with-react-alice-carousel)

**Comment by maxmarinich** [comment]
Hi, @NoHop3! Please see base examples [here](https://maxmarinich.github.io/react-alice-carousel/). Use common css to customize your elements like in the example below: 

<img width="1431" alt="Снимок экрана 2022-05-02 в 15 32 09" src="https://user-images.githubusercontent.com/9882979/166234291-d72ae337-0ff5-4240-8958-d258fb3404ba.png">
