### ISSUE TITLE
`keyboardNavigation` doesn't trigger `onSlideChange` or `onSlideChanged`

### ISSUE THREAD

**Issue by dwknippers** [maxmarinich/react-alice-carousel#234]
Currently when `keyboardNavigation` is set on the carousel,
the `onSlideChange` or `onSlideChanged` events do not fire.

This is problematic whenever custom components are used for
navigation and thumbnails.

Let me know if you need any more info, thank you so much for
writing this library. The rest has been working wonderfully ✨

**Comment by dwknippers** [comment]
Actually setting `keyboardNavigation` seems to not be having any effect. It's still possible to navigate via keyboard without this setting, preventing a manual fix. That's quite unfortunate.

**Comment by maxmarinich** [comment]
Hi, @dwknippers! Please check with next config and provide a code sample if problem won't resolve:

```js
import "./styles.css";
import React from "react";
import AliceCarousel from "react-alice-carousel";
import "react-alice-carousel/lib/alice-carousel.css";

export default function App() {
  const itemsLength = Array.from({ length: 5 });

  const items = itemsLength.map((item, index) => {
    const style = { height: 200 + index * 10 };
    return <div className="item" style={style} data-value={index + 1} />;
  });
  return (
    <div className="App">
      <AliceCarousel
        autoHeight
        animationType="fadeout"
        keyboardNavigation
        onSlideChange={(e) => {
          console.log("__Change:", e);
        }}
        onSlideChanged={(e) => {
          console.log("__Changed:", e);
        }}
        items={items}
      />
    </div>
  );
}
```

Looks like an incorrect issue:

<img width="1379" alt="Снимок экрана 2022-05-02 в 16 19 22" src="https://user-images.githubusercontent.com/9882979/166240897-a7d32c60-d731-4b7c-ba13-4e2659ecaaeb.png">
