### ISSUE TITLE
mouseDragEnabled isn't working

### ISSUE THREAD

**Issue by yenly** [maxmarinich/react-alice-carousel#24]
Hi! Just want to report that mouseDragEnabled doesn't seem to be working. I created a sample app using codesandbox. You can see the bug here: https://codesandbox.io/s/8zymljmp40

Am I using it wrong?

**Comment by yenly** [comment]
I also noticed the swiping and layout on mobile chrome is a bit weird. It's showing more than 1 slide. When I swipe to 2nd photo, it sometimes jump back to display the first one.

**Comment by maxmarinich** [comment]
Hi, @yenly! MouseDragEnabled works like expected. You should handle `drag` event independently like this: 
```
function prevent (e) {e.preventDefault()} 
// ...
<img
       src="https://placekitten.com/400/300"
      alt="Image 1"
      onDragStart={prevent}
      className="yours-custom-class"
 />
// ...
```

or looks example here: [https://codesandbox.io/s/8zymljmp40](https://codesandbox.io/s/8zymljmp40)

**Comment by maxmarinich** [comment]
> I also noticed the swiping and layout on mobile chrome is a bit weird. It's showing more than 1 slide. When I swipe to 2nd photo, it sometimes jump back to display the first one.

looks like mobile's problem only (your example tested), investigate is needed

**Comment by yenly** [comment]
Thank you, @maxmarinich!
