### ISSUE TITLE
Small question related with animation

### ISSUE THREAD

**Issue by TikoAbelyan** [maxmarinich/react-alice-carousel#240]
```
 <AliceCarousel 
       animationType="fadeout"
       animationDuration={2800}
       disableDotsControls={false}
       items={items}
       activeIndex={activeIndex}
       responsive={responsive}
       onSlideChanged={syncActiveIndex} 
  />
```

It's a multiply carousel, but animation don't working. there are methods any fix that problem?
When using without multiply carousel it worked.
Thx

**Comment by maxmarinich** [comment]
Hi, @TikoAbelyan! I guess you mutate props passed to the carousel. For example, like in this [issue](https://github.com/maxmarinich/react-alice-carousel/issues/239). Try to save `items` & `responsive` props in the component state. Probably look at [this](https://maxmarinich.github.io/react-alice-carousel/#custom-components) demo.
If you won't resolve the issue, provide full code sample.
