### ISSUE TITLE
Alice Carousel when there is no items to render 

### ISSUE THREAD

**Issue by innotech-ahmad-barghouthi** [maxmarinich/react-alice-carousel#241]
Hello,
I think that this component is just awesome but wondering if there is some custom component to render when there's no items in the carousel 
like the following:
![image](https://user-images.githubusercontent.com/71375627/171447997-e4b7421b-76f6-4251-a07a-8c70620832ca.png)

I searched for that but it seems not implemented yet

**Comment by maxmarinich** [comment]
Hi @innotech-ahmad-barghouthi. I think it's redundant. If the elements are missing, you should not show the gallery.
