### ISSUE TITLE
preservePosition prop, and how to freeze position when adding / updating elements

### ISSUE THREAD

**Issue by lucasriondel** [maxmarinich/react-alice-carousel#243]
Hey !

I saw that `AliceCarousel` has a prop called `preservePosition` but it is not listed in the documentation. What does it do ? 

Your lib is perfect for my need but unfortunately, when dynamically adding elements to my carousel, it goes back the the first slide. Is it possible to bypass this behavior by any mean ?

**Comment by maxmarinich** [comment]
Hi @lucasriondel! The savePosition property from v1. Please use v2. If you need to keep the previous position while passing new elements, use a pre-saved `activeIndex`. Almost similar [example](https://maxmarinich.github.io/react-alice-carousel/#custom-components-props).
