### ISSUE TITLE
onSlideChanged is inconsistant on react 18

### ISSUE THREAD

**Issue by u007** [maxmarinich/react-alice-carousel#245]
it works fine on react 17, but on react 18,
the event onSlideChanged e.item seems to be inconsistant. 
the last slide will always return the item of index before last.

**Comment by Cloeniveau** [comment]
I observe the same problem ! 
I'm working on react 18 too, and when I click ont dots, the event give the correct index, but when I drag the slides on the responsive caroussel, it returns always  the index of item before the current item.

**Comment by maxmarinich** [comment]
Hello! Yes, the issue associated with batching from v1.18. Fixed in #248 (v.2.6.4).
