### ISSUE TITLE
Carousel not rendering child item when using SSR

### ISSUE THREAD

**Issue by ion-willo** [maxmarinich/react-alice-carousel#25]
When using SSR items inside the carousel are not being rendered.

**Comment by maxmarinich** [comment]
@ion-willo , please provide code!

**Comment by ion-willo** [comment]
Hi @maxmarinich ,

See this quick demo repo:
https://github.com/ion-willo/alice-ssr

**Comment by ion-willo** [comment]
Hi @maxmarinich ,

Any news/feedback?

**Comment by maxmarinich** [comment]
Hi, @ion-willo! Works like expected if i use next SSR-kits [react-redux-hmr-ssr](https://github.com/maxmarinich/react-redux-hmr-ssr) && [create-react-app](https://github.com/facebook/create-react-app). In your case i need much time. With high probability, I'll be able to answer you today / tomorrow.

**Comment by ion-willo** [comment]
Awesome @maxmarinich , thank you.

**Comment by maxmarinich** [comment]
@ion-willo, sadly( I shouldn't spent my time to trying reproduce an contrived bug.
looks here: [report](https://www.youtube.com/watch?v=p3CHXoI3jVc)

**Comment by francescovenica** [comment]
I'm having the same problem using nextjs and ssr, is there something particular I need to do in order to enable ssr for the children?

**Comment by yogeshkotadiya** [comment]
Carousel is not working with Next.js SSR `getServerSideProps`, Although It's getting initialized on client-side hydration. But it doesn't render Elements in SSR HTML.

**Comment by maxmarinich** [comment]
Fixed in v1.19.3
