### ISSUE TITLE
Multiple on a page with 5 slides one renders 5.2

### ISSUE THREAD

**Issue by websuits** [maxmarinich/react-alice-carousel#253]
Hi,

I have 2 slides on a page with responsive configs set to  991: { items: 5 }.
On page load one loads 5, and the second loads 5 sliders + a little bit of the 6th.

If i resize, then the slider reconfigures and shows correctly 5 slides.

Page load
<img width="676" alt="Screenshot 2022-10-10 at 12 26 13" src="https://user-images.githubusercontent.com/42982977/194835761-a40401a5-9854-48c1-9c53-826458535b9c.png">

After i resize the window a little bit
<img width="591" alt="Screenshot 2022-10-10 at 12 26 21" src="https://user-images.githubusercontent.com/42982977/194835764-56f7fc45-b38a-486a-9380-9f64e6987f39.png">

Code is pretty simple:

 const responsiveSliderProducts = {
            0: { items: 2 },
            767: { items: 3 },
            991: { items: 5 }
};

 <AliceCarousel
                  items={ productsList }
                  responsive={ responsiveSliderProducts }
/>

It seems that the broken carousel will have a slide smaller than a slide in the correct rendered carousel.

**Comment by websuits** [comment]
As a workaround currently i've added another breakpoint of 1200: { items: 5 }. This seems to work for the moment.

**Comment by maxmarinich** [comment]
Hi, @websuits! The lib not works with decimal props. Use `stagePadding` instead. 
Like in the next examples: https://maxmarinich.github.io/react-alice-carousel/#stage-padding
