### ISSUE TITLE
Smoother Resizing Issue

### ISSUE THREAD

**Issue by emanuallan** [maxmarinich/react-alice-carousel#267]
Hello! First of all, this is a wonderful component-- very nice job! 

I attached a video and have posted my Carousel settings down below. Just wanted to ask if perhaps you know of any optimizations to make the component resize a little smoother. As you can see from the video, the component sometimes struggles to resize along with the window or attempts to do it after somewhat of a delay. Just trying to smoothen that out at the moment though am struggling. 

Let me know if you have any pointers! Thank you!

https://www.loom.com/share/fc68501452004397bf83505c6d199557

```
<AliceCarousel
        autoHeight
        activeIndex={activeIndex}
        onSlideChanged={onSlideChanged}
        responsive={{
          0: {
            items: 1,
          },
        }}
        autoPlay
        animationDuration={450}
        infinite
        autoPlayInterval={10000}
        mouseTracking
        items={getExploreItems()}
        renderDotsItem={dotItem => {
          return (
            <PageButton selected={dotItem.isActive}>
              {dotItem.activeIndex + 1}
            </PageButton>
          );
        }}
        disableButtonsControls
      />
```

**Comment by maxmarinich** [comment]
Hi, @emanuallan! It's redundant feature. There are no real cases for use that behavior.
