### ISSUE TITLE
How to make custom component disabled/hidden?

### ISSUE THREAD

**Issue by NurulWahedQalqul** [maxmarinich/react-alice-carousel#275]
Hello, I have two custom components to render the next and previous icons. How can I make them disabled/hidden when there are no more items? 
Here's my code:
![image](https://user-images.githubusercontent.com/127097111/228478114-12c21819-e882-4493-8fb8-755f7cb6da97.png)
![image](https://user-images.githubusercontent.com/127097111/228480464-59d88566-1a2f-4ecf-aeb9-453837da7a74.png)

**Comment by Kevin-M-Zaleo** [comment]
you could use a state, tracking the current slideIndex
in your ´renderNextButton function´
just add something like
`
renderNextButton={()=>{
return (slideIndex+1 !== slides.length &&
<div>
Your Button
</div>
)
}}
`

**Comment by maxmarinich** [comment]
Hi, @NurulWahedQalqul! Accordingly the [docs](https://github.com/maxmarinich/react-alice-carousel#types), you can using `isPrevSlideDisabled || isNextSlideDisabled` props from `EventObject`. Demo https://maxmarinich.github.io/react-alice-carousel/#events.
