### ISSUE TITLE
swipeDelta for vertical movements

### ISSUE THREAD

**Issue by Kevin-M-Zaleo** [maxmarinich/react-alice-carousel#276]
Hy
is there a way to have something similar to the `swipeDelta` Param but for vertical TouchEvents.
On mobile i got the problem that i have an rather large carousel, taking up most of the screen.
when i am using `touchMoveDefaultEvents={false}` the site becomes sort of unusable on mobile devices with a smaller Viewport.
Is there a way to apply `swipeDelta` to horizontal touch movements?

**Comment by maxmarinich** [comment]
Hi, @Kevin-M-Zaleo! There is no that possibility for a vertical swipes. I think all necessary cases are covered by the current behavior. And using `touchMoveDefaultEvents` with false is a very specific.
