### ISSUE TITLE
How to avoid irregular gaps between slides with different widths?

### ISSUE THREAD

**Issue by PabloMessina** [maxmarinich/react-alice-carousel#28]
Is there any support for variable width slides so as to avoid irregular gaps appearing between slides when items have different widths? Here is a screenshot:

![imagen](https://user-images.githubusercontent.com/6187545/44188867-6dd6e900-a0f6-11e8-93ca-5a34e8d7e1af.png)

Thanks for the awesome component!

**Comment by maxmarinich** [comment]
Hi @PabloMessina! The carousel hasn't a mechanism for the smart gaps. It will be included in the next versions.
