### ISSUE TITLE
move arrow position

### ISSUE THREAD

**Issue by salicius** [maxmarinich/react-alice-carousel#281]
hi, in the readme images carousels navigation arrows are to the sides while in the demo webpage are below the dots. How can i put them to the sides ?

**Comment by maxmarinich** [comment]
Hi, @salicius! Use common css with [classes](https://github.com/maxmarinich/react-alice-carousel#css-classes) like on the screenshot, custom component using the [props](https://maxmarinich.github.io/react-alice-carousel/#custom-components-props) or [render](https://maxmarinich.github.io/react-alice-carousel/#custom-components-render) functions.

<img width="1413" alt="Screenshot 2023-05-12 at 15 28 37" src="https://github.com/maxmarinich/react-alice-carousel/assets/9882979/d9e1eccb-d666-45ad-8ece-3e865c87a235">
