### ISSUE TITLE
Support for CSS/SCSS modules

### ISSUE THREAD

**Issue by M1K3Yio** [maxmarinich/react-alice-carousel#286]
We are using this React component within our NX monorepo.  Currently we are importing this in a nextjs library, which we then import into our nextjs app.  While updating our version of nextjs, we identified as issue where [Global CSS Must Be in Your Custom <App>](https://nextjs.org/docs/messages/css-global) which recommends imports within `app.js` or css modules, which is the best approach. 

```
Failed to compile.

../../node_modules/react-alice-carousel/lib/alice-carousel.css
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
```

**Comment by maxmarinich** [comment]
Hi, @M1K3Yio! Provide the code samle. What's about: 
```js
@import "react-alice-carousel/lib/scss/alice-carousel.scss"
```
