### ISSUE TITLE
Carousel Memory Leak

### ISSUE THREAD

**Issue by ElsonNezaj** [maxmarinich/react-alice-carousel#287]
"Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method."
This happens when a component that uses the carousel unmounts. The react state is cleared everytime the components are unmounted , but still the error occurs

**Comment by maxmarinich** [comment]
Hi, @ElsonNezaj! The library already has all preparations to unsubscribe and it uses them as expected. The problem is probably within your component. 
If not reopen the issue and provide a code sample.
