### ISSUE TITLE
images to the left instead of center

### ISSUE THREAD

**Issue by hamzapaskingakhtar1999** [maxmarinich/react-alice-carousel#288]
I am trying to add an item container that has image. title and price. Everything is fine but image is to the left. Rendering same without using React-alice is fine. 

Also in smaller screens instead of being in the middle the container is moved to the right. No margins of the container.

**Comment by maxmarinich** [comment]
Hi, @hamzapaskingakhtar1999! 
The lib is using `inline-block` model to display & groups elements.
Use samples from [here](https://maxmarinich.github.io/react-alice-carousel/). Open the dev console and check the styles for the case you are interested in. 
You can specify any styles for internal [classnames](https://github.com/maxmarinich/react-alice-carousel#css-classes)
