### ISSUE TITLE
Misnamed import?

### ISSUE THREAD

**Issue by kschrader02** [maxmarinich/react-alice-carousel#29]
I just installed this library and the latest typescript defs. When I import AliceCarousel it says the import should be named 'reactAliceCarousel' instead of 'AliceCarousel' when I try to compile, but if I change it then it says that property reactAliceCarousel is not a JSX.IntrinsicElement. I expect this to work out of the box, any idea why it is not? I removed my node_modules folder and did an update and install and it is still having the same problem.

**Comment by maxmarinich** [comment]
@kschrader02, could you provide error description?

**Comment by kschrader02** [comment]
@maxmarinich When I do `import AliceCarousel from 'react-alice-carousel';`
(4,1): Misnamed import. Import should be named 'reactAliceCarousel' but found 'AliceCarousel'

That's all it tells me. It is fine with the basic carousel I've put in my render function, but it won't compile due to the misnamed import issue even though I believe that is the intended name.

**Comment by maxmarinich** [comment]
I've created an [example](https://github.com/maxmarinich/react-alice-carousel/tree/types-example) with types, please try. It looks like not the library issue.
