### ISSUE TITLE
react alice carousel alice-carousel__stage-item width not updating on parent element resize

### ISSUE THREAD

**Issue by VinayaSonawane-hspl** [maxmarinich/react-alice-carousel#292]

**Comment by maxmarinich** [comment]
Hi, @VinayaSonawane-hspl! Please, provide the code sample and add description for the issue.

**Comment by maxmarinich** [comment]
Use common css to resolve your issue. The carousel are resizing if root element with the classname `.alice-carousel` have changed dimensions. I guess you use flexbox model and it has some peculiarities with calculation. Check base [examples](https://maxmarinich.github.io/react-alice-carousel/) and se how the resize working.

**Comment by VinayaSonawane-hspl** [comment]
@maxmarinich I'm using material ui container. Inside container I've used alice carousel.
.alice-carousel don't change it's width when outer (container) resize due to menu open/ close.

I've not used flexbox model here.

**Comment by VinayaSonawane-hspl** [comment]
@maxmarinich is there any solution on alice container update ?
as it's working well on window resize, but issue is there when internal item open/close (menu in my project).
