### ISSUE TITLE
Is there a way to have an onUpdate method?

### ISSUE THREAD

**Issue by bogdancss** [maxmarinich/react-alice-carousel#293]
Is there a way to have an onUpdate method?

I need to know the itemsInSlide after I add new items to the carousel.

I set this to a visibileItems state through the onInitialise and onResize methods, but I'd need it on and onUpdate as well

**Comment by maxmarinich** [comment]
Hi, @bogdancss! You don't need any event to check if any element is new. Because you are passing props (like items) from above. After all, if you passed the updated props to the carousel, you fire the update event yourself. Events example is [here](https://maxmarinich.github.io/react-alice-carousel/#events)

**Comment by bogdancss** [comment]
Hei @maxmarinich  I get that, but we have a check that disables the prev/next carousel buttons based on `isNextSlideDisabled` and `isPrevSlideDisabled` from the carousel `EventObject`
I get access to this event in the `onResized` and `onInitialized` methods which works fine on init or resize.

However we have the ability to add/remove items after init - when we add/remove am item to/from the carousel, we need to update the prev/next buttons. Obviously the `onResized` and `onInitialized` methods are not triggered here, so there is no way to determine if these buttons should be active or not.

**Comment by bogdancss** [comment]
@maxmarinich I noticed the Update event is there, just there is not way to subscribe to it:

`enum EventType {
  ACTION = 'action', // used if a general user action (button click or swipe)
  INIT = 'init',     // used if the initial event was triggered
  RESIZE = 'resize', // used if the gallery size was changed
  UPDATE = 'update', // used if the gallery was updated with props (activeIndex)
}`
