### ISSUE TITLE
Scroll by more than 1 item.

### ISSUE THREAD

**Issue by stefan1968** [maxmarinich/react-alice-carousel#30]
If I say have 4 thumbnails I want to scroll, is it possible to scroll via the width of all 4 items, rather than the 1 item at a time? 

So, the whole carousel bar does a quick scroll and the display items are in the same order once it's completed?

**Comment by maxmarinich** [comment]
Hi @stefan1968. Possible, this is a bug. The fix is in progress.

**Comment by maxmarinich** [comment]
fixed in [02bbb9c ](https://github.com/maxmarinich/react-alice-carousel/commit/3fba1d0148ff5829916873b7ff0939ae20574d9e)
