### ISSUE TITLE
Centering the items

### ISSUE THREAD

**Issue by AmirAmArA** [maxmarinich/react-alice-carousel#301]
hey there, 
ive stumblled upon this package , 
and I am trying to use it but I can't seem to figure out how to center the items of the slider 

![image](https://github.com/maxmarinich/react-alice-carousel/assets/39839322/a384278e-ea54-4d73-9fd5-c71ce3b49ddc)

**Comment by NoxQ** [comment]
Try centering the divs like this maybe

```
const items = [
    <div className="item"  align="center" data-value="1">1</div>,
...
];
```
Or if using Tailwind just use `mx-auto`

**Comment by maxmarinich** [comment]
Hi, @AmirAmArA! Use common css. 
```css
.item {
  margin: auto;
}
```

**Comment by AmirAmArA** [comment]
it appears that I was using disabling scrolling on the X-axis, which didn't allow me to see what was the full problem, 
a simple width property to align with the viewport width solved the problem 
`  width: 100%;
`
