### ISSUE TITLE
Responsive not working well on desktop view

### ISSUE THREAD

**Issue by EmmanuelVictor62** [maxmarinich/react-alice-carousel#304]
Hello @maxmarinich , 
I have a page where I am currently using the slider and the responsive viewport at over 1000 is set to 2, but the slider returns 2 items and a half of the third one, the expected behavior is for the 2 items to take up the space completely

![image](https://github.com/maxmarinich/react-alice-carousel/assets/104584134/4cb9bdc7-7ffb-4c7c-9aa3-6b81bf4e3771)

```
 const [responsive] = useState({
    0: { items: 1 },
    1000: { items: 2 },
  });

<Carousel responsive={responsive}>{items?.map}</Carousel>

<div className={styles["carousel__wrapper"]}>
      <CarouselButton icon="arrowLeftCircle" onClick={handlePrevButtonClick} />
      <AliceCarousel
        disableDotsControls
        disableButtonsControls
        disableSlideInfo
        mouseTracking
        responsive={responsive}
        ref={carouselRef}
        keyboardNavigation
      >
        {children}
      </AliceCarousel>
      <CarouselButton icon="arrowRightCircle" onClick={handleNextButtonClick} />
    </div>
    
```

**Comment by maxmarinich** [comment]
Hey @EmmanuelVictor62! Looks like there is a problem with your CSS. You should create a complete example on any public service (eg https://codesandbox.io) or git repo.

**Comment by EmmanuelVictor62** [comment]
Thanks for the reply @maxmarinich, I have been able to identify the issue
