### ISSUE TITLE
No Styling for Next Button

### ISSUE THREAD

**Issue by abhinaypawar470** [maxmarinich/react-alice-carousel#306]
![Screenshot 2024-02-11 010649](https://github.com/maxmarinich/react-alice-carousel/assets/122138361/cf52578b-dcd6-4add-86c2-2eb9b05573c8)
https://github.com/maxmarinich/react-alice-carousel/blob/93f6b0741e97c2b2ea92ffcf966abf2a78fd4a35/src/lib/scss/alice-carousel.scss#L92
the next button is not perfectly aligned. It should align to left, it inherits the parent's styling which was center.

**Comment by hunxjunedo** [comment]
please be more clear and specific regarding the issue.

**Comment by maxmarinich** [comment]
Fixed at #307

**Comment by mt4110** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
jjetwong, @aindrajaya, @jona799t, @snowsky, @DavidY2014, @welly87, @3atharvkurdukar, @simulacra10, @MutatedBread, @Flouse, @andrewyang95, @Balianos, @0xnim, @khangaridb, @mkellnhofer, @ratul1214, @lewandy, @jmayalag, @Provoo, @Hardstuck

**Comment by abhinaypawar470** [comment]
Suggested changes were pulled to main branch of alice Carousel
