### ISSUE TITLE
Feature request: Change dots container styles

### ISSUE THREAD

**Issue by dogfrogfog** [maxmarinich/react-alice-carousel#310]
would love to see the way to override dots container styles or pass function to dots container

**Comment by dogfrogfog** [comment]
current solution is to override from global.css:
```
.alice-carousel__dots {
  margin: 0 !important;
}
```

**Comment by maxmarinich** [comment]
Hi, @dogfrogfog! The implementation an additional functionality is redundant for this issue. Use common solution: 
```css
ul.alice-carousel__dots {
    margin: 0;
}
```
