### ISSUE TITLE
Error with the import of AliceCarousel

### ISSUE THREAD

**Issue by Sagbyy** [maxmarinich/react-alice-carousel#311]
```js
import AliceCarousel from 'react-alice-carousel'
import 'react-alice-carousel/lib/alice-carousel.css'
```

Uncaught SyntaxError: The requested module '/node_modules/react-alice-carousel/lib/react-alice-carousel.js?v=3e305248' does not provide an export named 'default'

**Comment by maxmarinich** [comment]
Hi, @Sagbyy! Looks like the issue with your module bundler. Provide more info about it (lib version, bundler type and etc). Please, reopen the issue if problem will exist after module bundler tuning with link to [codesandbox](https://codesandbox.io/) or git repo.
