### ISSUE TITLE
Encountering JS Error

### ISSUE THREAD

**Issue by abhishek871** [maxmarinich/react-alice-carousel#322]
function(e, t, n) {
        "use strict";
        Object.defineProperty(t, "__esModule", {
            value: !0
        }),
        t.DotsNavigation = void 0;
        var a = o(n(4))
          , i = o(n(2))
          , r = function(e) {
            if (e && e.__esModule)
                return e;
            var t = {};
            if (null != e)
                for (var n in e)
                    Object.prototype.hasOwnProperty.call(e, n) && (t[n] = e[n]);
            return t.default = e,
            t
        }(n(315));
        function o(e) {
            return e && e.__esModule ? e : {
                default: e
            }
        }
        (t.DotsNavigation = function(e) {
            var t = e.state
              , n = e.onClick
              , i = e.onMouseEnter
              , o = e.onMouseLeave
              , s = t.slides
              , c = t.items
              , l = t.infinite
              , d = r.itemInfo(t).isNextSlideDisabled
              , p = r.getDotsNavigationLength(s.length, c);
            return a.default.createElement("ul", {
                className: "alice-carousel__dots"
            }, s.map((function(e, u) {
                if (u < p) {
                    var m = r.isTheLastDotIndex(u, l, p)
                      , h = r.getItemIndexForDotNavigation(u, m, s.length, c)
                      , f = r.getActiveSlideIndex(d, t) === u ? " __active" : "";
                    return a.default.createElement("li", {
                        key: "dot-item-" + u,
                        onClick: function() {
                            return n(h)
                        },
                        onMouseEnter: i,
                        onMouseLeave: o,
                        className: "alice-carousel__dots-item" + f
                    })
                }
            }
            )))
        }
        ).propTypes = {
            state: i.default.object.isRequired,
            onClick: i.default.func.isRequired,
            onMouseEnter: i.default.func.isRequired,
            onMouseLeave: i.default.func.isRequired
        }
    },

For above code I am getting a JS Error :
"TypeError: s.map is not a function at t.DotsNavigation [as constructor]".

Please help to resolve this JS error.As I think It only needs a sanity check to be taken before accessing .map over "s".

**Comment by abhishek871** [comment]
Please help with this error resolution

**Comment by maxmarinich** [comment]
Hi, @abhishek871! The issue is related to the build settings.

**Comment by shivamjuyal19** [comment]
Thanks @maxmarinich for fixing this.
