### ISSUE TITLE
show little preview of next slide

### ISSUE THREAD

**Issue by iBasit** [maxmarinich/react-alice-carousel#34]
I want to show small part of the next slide if exists, how can I do that? via css or some other parms?

![image](https://user-images.githubusercontent.com/34341/45822845-3aced900-bce4-11e8-8e2c-e46dd1bf3d11.png)

**Comment by iBasit** [comment]
I have tried looking for different carasol to implement, but this is the far best lib, just need sides to be displayed, so users know there is more div on right or left side, so we don't have to show arrows.

**Comment by maxmarinich** [comment]
Hi, @iBasit, sorry for the late answer! The feature you needed will be implemented soon. Thanks for the feedback.

**Comment by iBasit** [comment]
@maxmarinich 

This is probably not the best solution if someone needs to show left and right, but it works well with showing a little bit on the right side using the following method. 

![image](https://user-images.githubusercontent.com/34341/45880338-7a0e3000-bd9f-11e8-9234-d1b13825ea0a.png)

**Comment by maxmarinich** [comment]
@iBasit 
There're some solutions for the feature. I need to analyze the most popular of them. Now I am engaged in global refactoring(tests, build, demo git pages). And i'll implement the feature after it.

**Comment by iBasit** [comment]
Thank you for quick response. 

check following lib, its for react-native, but demo is really nice.
https://github.com/archriss/react-native-snap-carousel

![image](https://camo.githubusercontent.com/7590ec7e6b705a6e8e381397247d576c6db72147/68747470733a2f2f692e696d6775722e636f6d2f653157625a63752e676966)

looking forward for the feature

**Comment by maxmarinich** [comment]
Thanks @iBasit!

**Comment by xeoneux** [comment]
Hey @maxmarinich, loving this library!

I would like to use this feature as well.

Right now I'm setting the items key in responsive as a decimal. Something like `4.5`.

This does the job but causes the first image to be partially visible instead of the last one 😸

**Comment by bernardodestefano** [comment]
Hi @maxmarinich ,
tried several carousel but this one is my favourite, just need that feature to be perfect!

**Comment by iBasit** [comment]
> This does the job but causes the first image to be partially visible instead of the last one 😸

I have tried this one as well, does not work well for different sizes. 

seems like lots of people wanting this same feature to be implemented.  The only way to implement it properly is by digging in the library, hopefully, @maxmarinich will have something for us soon if we are lucky :)

**Comment by bernardodestefano** [comment]
Hey @maxmarinich, 
any updates about this feature? :)

**Comment by maxmarinich** [comment]
Hi, @bernardodestefano! The feature in the testing phase.

**Comment by maxmarinich** [comment]
Added in [a79e50](https://github.com/maxmarinich/react-alice-carousel/commit/a79e5055aee46bfaa9a8000dd098724ca3c6cc47)

**Comment by bernardodestefano** [comment]
@maxmarinich in order to use the feature i guess i should just specify items number like '1.2' to see 20% on the next card, is that correct? can't see anything about it on the docs :/

**Comment by maxmarinich** [comment]
Hi, @bernardodestefano! You should passed `stagePadding` property t.l.t.:   
      ` {
      paddingLeft: 50,
      paddingRight: 100,
  }`

**Comment by maxmarinich** [comment]
p.s.: number only

**Comment by trackmystories** [comment]
Hey, How do i add images to the Alice Carousal. After installing it on my react application it doesn't seem to render images.

**Comment by trackmystories** [comment]
Hello, it seems I have resolved the issue. thank you here is the code I used to display a slide with logo's 
   `    <AliceCarousel
        duration={1000}
        fadeOutAnimation={true}
        mouseDragEnabled={true}
        onSlideChanged={console.debug}
        infinite={true}
        responsive={this.responsive}
        stagePadding={this.stagePadding}
        autoPlayInterval={1000}
        autoPlayDirection="rtl"
        autoPlay={true}
        playButtonEnabled={false}
        disableAutoPlayOnAction={false}

      >
        <div className="item"><Image width={64} height={64} className="logo-png" src={} alt= "Logo" /></div>
        <div className="item"><Image width={64} height={64} className="logo-png" src={} alt= "Logo" /></div>
        <div className="item"><Image width={64} height={64} className="logo-png" src={} alt= "Logo" /></div>
        <div className="item"><Image width={64} height={64} className="logo-png" src={} alt= "Logo" /></div>
        <div className="item"><Image width={64} height={64} className="logo-png" src={} alt= "Logo" /></div>
        <div className="item"><Image width={64} height={64} className="logo-png" src={} alt= "Logo" /></div>
        <div className="item"><Image width={64} height={64} className="logo-png" src={} alt= "Logo" /></div>

      </AliceCarousel>`

**Comment by R9295** [comment]
```stagePadding``` doesn't seem to be a property anymore. Is there a more updated way to do this now? I couldn't find anything in the README

**Comment by maxmarinich** [comment]
> `stagePadding` doesn't seem to be a property anymore. Is there a more updated way to do this now? I couldn't find anything in the README

The current version is v2, `stagePadding` property use in v1 only. The readme describes all info!

**Comment by JyotiMarwal** [comment]
> Hi, @bernardodestefano! You should passed `stagePadding` property t.l.t.:
> ` { paddingLeft: 50, paddingRight: 100, }`

thanks....it helps me alot
