### ISSUE TITLE
Feature request: slideNext/slidePrev with index 

### ISSUE THREAD

**Issue by sos0** [maxmarinich/react-alice-carousel#36]
I would love to be able to call something like: `this.Carousel._slidePrevPage()` or `this.Carousel._slidePage(count)` to slide the entire # of slides designated for the `responsive` setting instead of navigating one slide at a time. Would this be a doable and/or reasonable feature to request?

My current solution was to write a function like this:
```js
  pageHandler = (slideCount) => {
    // If the current number of slide items are just 1, do not divide by 2. If current number is > 1, slide page by # items/2.
    let responsiveSlideCount = slideCount > 1 ? slideCount/2 : 1;
    // Alternative version:
    // let responsiveSlideCount = slideCount > 5 ? slideCount/2 : slideCount;
    let itemIndex = this.Carousel.state.currentIndex + responsiveSlideCount;
    if (itemIndex < 0) {
      itemIndex = 0;
    }

    this.Carousel._slideToItem(itemIndex);
  }
```
```jsx
<button className="slide-button-back" onClick={() => this.pageHandler(this.Carousel.state.items * -1)}>
  <i className="fa fa-caret-left" />
</button>
<button className="slide-button-next" onClick={() => this.pageHandler(this.Carousel.state.items)}>
  <i className="fa fa-caret-right" />
</button>
```

**Comment by maxmarinich** [comment]
Hello @sos0! The function you need breaks the logic. Because in this case there is no clear determination for a next page or a slide. Also it'll affect the many handlers(swiping, autoplay...). To implement this functionality you should use `slideToIndex` property. In the next version, I will expand the functionality to get detailed information about the state of the carousel. Then I will describe an example for your case.

**Comment by sos0** [comment]
@oyeanuj You can probably temporarily use my solution (just modify responsiveSlideCount to be what you need). You can use `this.Carousel._slideToItem(index)` to change the behaviors for your back/next buttons.

**Comment by maxmarinich** [comment]
@sos0, promised [example](https://github.com/maxmarinich/react-alice-carousel#example-for-slideprevslidenext-page) (from >= v. 1.13.0)
