### ISSUE TITLE
How to add padding between items in slide when using multiple items in the slide 

### ISSUE THREAD

**Issue by duongthienlee** [maxmarinich/react-alice-carousel#42]
In the example image, it shows the padding between those items, but I couldn't find any props to do that

**Comment by maxmarinich** [comment]
Hi, @duongthienlee! Use ordinary css to set padding inside a gallery item. There are no props for this in the gallery.

**Comment by duongthienlee** [comment]
Oh, I did not think about that. Thank you for your suggestion. Anyways, great lib
