### ISSUE TITLE
adaptive height

### ISSUE THREAD

**Issue by eballeste** [maxmarinich/react-alice-carousel#48]
wondering what the best way would be to adapt the height of the container to adjust to the height of the current slide... my initial thought was to maybe use refs and tap into the `onSlideChanged` method to maybe set an explicit height but not sure if this is recommended or not... looking for suggestions, thanks!

**Comment by maxmarinich** [comment]
Hi, @eballeste. The most elegant way to get `auto height` is a new feature request. I'll try to implement it in a few days.

**Comment by maxmarinich** [comment]
Implemented at [v1.14.0](https://github.com/maxmarinich/react-alice-carousel/commit/a0794179e5a0efc01e10cd2adb7a08116fa91b40)
