### ISSUE TITLE
When rendering forms inside carousel using children, props not propagated

### ISSUE THREAD

**Issue by adamloving** [maxmarinich/react-alice-carousel#49]
To repro
Use a form element in one of the slides (children)
Have an onChange handler on that input that causes the state of a container component to change and pass new props to the slide

Expected
* The input is updated with the changed prop value

Actual
* The input is not re-rendered

I think this `if` statement needs to also check if `this.props.children` have changed (since children can either be in `props.children` or `props.items`. 
https://github.com/maxmarinich/react-alice-carousel/blob/543297b4bbb238d3ac0e0fee7a5d037a02a25c78/app/components/react-alice-carousel.js#L67

**Comment by maxmarinich** [comment]
Hi, @adamloving! `children` are always new (`this.props.children !== prevProps.children` are always `true`). It's preferable to use `items` instead `children`. You can provide me the code sample like [here](https://codesandbox.io/s/vq1y9z3x80), i''ll try how it works.
