### ISSUE TITLE
Requires react-hot-loader but does not have it as a dependency

### ISSUE THREAD

**Issue by JayAshday** [maxmarinich/react-alice-carousel#52]
I was just upgrading react-alice-carousel from 1.13.1 to 1.13.8, and after doing so I get the following error message: `Module not found: Can't resolve 'react-hot-loader' in 'node_modules/react-alice-carousel/lib'`.

Installing the latest version of the react-hot-loader package fixes this.

If this is a new dependency of react-alice-carousel, could it be made either a dependency or peerDependency in the package.json file?

**Comment by maxmarinich** [comment]
Hi @JayAshday! Please update to v1.13.10 and try again.

**Comment by JayAshday** [comment]
Thanks; this seems to be fixed now.
