### ISSUE TITLE
"tabbing" between slides breaks carousel 

### ISSUE THREAD

**Issue by jaabiri** [maxmarinich/react-alice-carousel#53]
Currently if there are multiple buttons spanning multiple slides, tabbing between them causes the carousel to get stuck halfway between slides.

**Comment by maxmarinich** [comment]
@jaabiri, please provide a correct code sample like [here](https://codesandbox.io/s/vq1y9z3x80). The behavior is correct in your example.

**Comment by jaabiri** [comment]
https://codesandbox.io/s/xpv33387oz

**Comment by maxmarinich** [comment]
@jaabiri, clarify the problem.

**Comment by maxmarinich** [comment]
if you about `padding`, reset [values](https://i.imgur.com/mkoGeUn.jpg) for a gallery item in css
`.alice-carousel__stage-item {
    padding: 0;
}`

**Comment by maxmarinich** [comment]
> https://codesandbox.io/s/xpv33387oz

not works
