### ISSUE TITLE
responsive property causes multiple mounts on components

### ISSUE THREAD

**Issue by jmdelgadoh** [maxmarinich/react-alice-carousel#54]
I am using the carouself to render a few components, not just simple img tags.

These components use lifecycle methods and are stateful, because depending on some props from redux store, they change the URL of the image they render. 

The issue im having is that by using the responsive property, the carousel appears to be remounting all components multiple times, which causes multiple triggers on componentDidMount(), which are often async GET fetches, resulting in multiple fetches. 

It is not consistent in the sense that if i pass it 3 items it will mounts each twice, but rather, i pass it 3 items and it will remount all of them twice, then some of them a third time but not all.

My expected behavior was simply not multiple mounting of components. Is there a property i might be missing, or another way of passing stateful components to the carousel?

**Comment by maxmarinich** [comment]
@jmdelgadoh, could you provide a code sample?

**Comment by jfamousket** [comment]
![skill](https://user-images.githubusercontent.com/40635633/56192610-11ceb680-602f-11e9-9d82-1e250390cc4f.png)

**Comment by jfamousket** [comment]
I have the same problem this is the component I want to be rendered by the carousel

![skill](https://user-images.githubusercontent.com/40635633/56193039-0d56cd80-6030-11e9-85c2-043995609a14.png)

This is where I render it in the second carousel

![project](https://user-images.githubusercontent.com/40635633/56192712-480c3600-602f-11e9-962b-6e5faee8ec59.png)

This function render loops through an array of objects and returns an array, then I set the state skill items to the returned array

![render](https://user-images.githubusercontent.com/40635633/56192796-78ec6b00-602f-11e9-99f5-c41f8416a1e6.png)

**Comment by maxmarinich** [comment]
@jfamousket, please provide a code sample with  `codesandbox`, link is in comment above.

**Comment by jmdelgadoh** [comment]
hey @maxmarinich  so I went ahead and coded an example. I was unable to replicate the issue EXACTLY in codesandbox but the main issue still persists. The differnce is in my local app code, removing the 'responsive' prop seemed to fix my issue, while it didnt seem to fix it in this demo.

So to illustrate again, the issue is that if the items being passed to the carousel as [items] are components that do something on mount, they will get mounted multiple times. If you open the console you will see i am logging a message on mount, and it is mounting more times than they should be. This in my personal code translates to multiple unnecesary fetches, which is why it's a problem for me. 

I hope this helps, thanks for any feedback you can provide! 

https://codesandbox.io/embed/o48ly3lzz

**Comment by maxmarinich** [comment]
@jmdelgadoh, you should't use next code:
```javascript
export default class Carousel extends React.Component {
  // ...
  render() {
    const stagePadding = {
      paddingLeft: 50,
      paddingRight: 100
    };
    const responsive = {
      0: { items: 2  },
      1024: { items: 4 }
    };
    return (
      <AliceCarousel
        stagePadding={stagePadding}
        responsive={responsive}
       // ...
     />
    )
  }
}
```
Obviously, the gallery get `newProps` (stagePadding, responsive) every time, and get rerender.
Get `stagePadding` && `responsive` like this:

```javascript
export default class Carousel extends React.Component {
  stagePadding = {
    paddingLeft: 50,
    paddingRight: 100
  };
  responsive = {
    0: { items: 2  },
    1024: { items: 4 }
  };
  render() {
    return (
      <AliceCarousel
        stagePadding={this.stagePadding}
        responsive={this.responsive}
       // ...
      />
    );
  }
}
```
Please try and report.

**Comment by jmdelgadoh** [comment]
Hey just tried it but it doesnt seem to make a difference. Tried it in the codebox and also in my local code. A weird thing is that in my local app i dont have this issue of multiple mounts if i remove the responsive property, but codebox seems to present the issue even if i take responsive property off, which is why i cant exactly replicate both scenarios. I tried enabling and disabling other props but i can't see it make a difference.

I don't mind the re-rendering, the problem is multiple mounts. If it was just a re-render of the components inside it would not fire componentDidMount() method repeatedly.

**Comment by maxmarinich** [comment]
Hi everyone! The Carousel behavior is expected. Explanation: `componentDidMount` life cycle that called only once. If you assume that this has been called multiple times, then the component has been presented multiple times. In our case, components were mounted only once. If you update the [sandbox](https://i.imgur.com/eBYdNuo.jpg) a bit and look at the [screenshot](https://i.imgur.com/WIHhEm7.jpg), you'll see what really happened. The gallery must clone some elements to manipulate the animation.

**Comment by jmdelgadoh** [comment]
So you're saying the gallery component itself is being cloned and mounted multiple times? where is that cloning happening then? What could be changed in that code to prevent that from happening? I am only mounting the carousel once, so i wouldnt expect it to mount my images more than once, is the error somewhere in the creation of the items array? 

I appreciate the explanation thanks

**Comment by maxmarinich** [comment]
@jmdelgadoh, the cloning some elements (not all) is an expected flow (not a bug).  The gallery must clone some elements to manipulate the animation.

**Comment by jmdelgadoh** [comment]
I understand the need to clone, ive cloned elements in my components before too, but i hadnt seen that cause a double mount, does it clone them after having mounted them? 

Thanks for the responses, if I have time ill take a look at the source code so i can fully understand what's happening, thanks!
