### ISSUE TITLE
Cant trigger onClick event inside gallery items.

### ISSUE THREAD

**Issue by Soumek** [maxmarinich/react-alice-carousel#55]
Hey! i'm using alice carousel to recreate this slider.
![desiredslider](https://user-images.githubusercontent.com/44204792/56226489-55322080-6041-11e9-83c2-99a6e1f82a53.png)
The problem is that i want to have that active item behavior(green one) i thought in having a component which has an active state, so clicking on the item activates it and it changes the component bellow with react-router-dom but onClick isnt working in the given item.

Here's the code.
![2019-04-16 12_23_57-HorizontalCarousel js - app2 - Visual Studio Code  Administrator](https://user-images.githubusercontent.com/44204792/56227024-8a8b3e00-6042-11e9-8640-aadfcee4c64c.png)
HCarouselItem Component
![2019-04-16 12_26_31-HCarouselItem js - app2 - Visual Studio Code  Administrator](https://user-images.githubusercontent.com/44204792/56227195-e5bd3080-6042-11e9-9567-c41837d23d28.png)
Here's the actual Carousel
![2019-04-16 12_27_14-React App](https://user-images.githubusercontent.com/44204792/56227237-01c0d200-6043-11e9-984e-ae205b6df2c0.png)

Please tell me if this is allowed in Alice Carousel or i messed up with the code, i dont know how to work with codepen but if you really need it i'll try my best. Thanks in advance.

**Comment by maxmarinich** [comment]
@Soumek, please provide a code sample like [this](https://codesandbox.io/s/m7k7rjnxrx).

**Comment by Soumek** [comment]
https://codesandbox.io/s/j7wo8xo93v Here's the code sample!

**Comment by maxmarinich** [comment]
@Soumek, you can only hang the handler on a real 'dom' element. In your case, you passed the handler as a property for react element <ActiveItem />(virtual dom) and should get it from the component's props. Correct code for your component:
```javascript
import React from "react";
import logo from "./assets/logo.jpg";

export default function NormalItem({ onClick }) {
  return (
    <div
      onClick={onClick}
      className="carouselitem d-flex align-items-center ml-4"
    >
      <div className="carouselitem-wrapper d-flex justify-content-center align-items-center">
        <img src={logo} />
      </div>
    </div>
  );
}

```
![Screenshot](https://user-images.githubusercontent.com/9882979/56415616-df26f700-6296-11e9-952f-b6f99d99d30e.jpg)

**Comment by Soumek** [comment]
Thank you very much!
