### ISSUE TITLE
Feature: Zoom Capability when Clicking on Image

### ISSUE THREAD

**Issue by rimatla** [maxmarinich/react-alice-carousel#56]
Thank you for this great Library, Does the API already offer Zoom capability? i.e:
> When triggering a **zoom** icon contained in the carousel, a given image would expand in a modal.

**Comment by maxmarinich** [comment]
Hi, @rimatla! I thought about it and decided not to overload the library. You can connect a third-party library ([react-medium-image-zoom](https://www.npmjs.com/package/react-medium-image-zoom), [react-image-zoom](https://www.npmjs.com/package/react-image-zoom) ) for a gallery item.
