### ISSUE TITLE
Draggable element inside Alice Carousel

### ISSUE THREAD

**Issue by uchami** [maxmarinich/react-alice-carousel#61]
Hi, 
I'm using the Carousel and I can't find a way to avoid the "mouseDrag" event to trigger on drag of an element inside the carousel.

`<AliceCarousel
						mouseDragEnabled
						responsive={{
							0: { items: 1 },
							900: { items: 2 },
							1124: { items: 3 },
							1500: { items: 4 },
						}}
						items={ [
<div className="p-3" style={{background: 'red'}}> 
	<div draggable="true" style={{background: 'black',cursor:'pointer'}} onDragStart={(e) => e.stopPropagation()} onDragExit={(e) => e.stopPropagation()}>Drag me 1!</div> 
</div>,
<div className="m-3"> 
	<div draggable="true" style={{cursor:'pointer'}} onDrag={(e) => e.stopPropagation()}>Drag me 3!</div> 
</div>,
<div className="m-3"> 
	<div draggable="true" style={{cursor:'pointer'}} onDrag={(e) => e.stopPropagation()}>Drag me 4!</div> 
</div>,
<div className="m-3"> 
	<div draggable="true" style={{cursor:'pointer'}} onDrag={(e) => e.stopPropagation()}>Drag me 5!</div> 
</div>] }
						infinite={false}
					>
					</AliceCarousel>`

If I click any of the divs, and I drag the click, it won't move the carousel right away, because of the stopPropagation(), but as soon as I release it, it will move the carousel.

Any ideas?

**Comment by maxmarinich** [comment]
Hi, @uchami! Please provide the correct code sample like [here](https://codesandbox.io/s/m7k7rjnxrx).

**Comment by uchami** [comment]
Sorry for that, there you go:

https://codesandbox.io/embed/reactalicecarousel-stage-padding-example-ykept?fontsize=14

I recommend watching it on full screen

**Comment by maxmarinich** [comment]
Why you added `draggable="true"` attribute?

**Comment by maxmarinich** [comment]
You should use `handleOnDragStart` for tags like `<img>` or '<a>'.

**Comment by uchami** [comment]
My goal is to implement a spinner inside cards that are in an Alice Carousel. I added draggable="true" beacuse that seemed to be needed to allow onDrag event to exist. What I really wanted to implement was associated with a spinner (that depends on other modules).

**Comment by maxmarinich** [comment]
> My goal is to implement a spinner inside cards that are in an Alice Carousel. I added draggable="true" beacuse that seemed to be needed to allow onDrag event to exist. What I really wanted to implement was associated with a spinner (that depends on other modules).

There's a very strange flow. Obviously there is not the library issue. But you can use other events to trigger `when an item loose focus`. E.g.: to emulate drag event flow use onMouseDown && onMouseUp events for a gallery item.

**Comment by uchami** [comment]
Clearly there is not a problem with the carousel, I just wanted to know if you've handled this kind of issues, given that you give support to a draggable library, and the issue is: I can't drag inside the draggable carousel.

Thanks for the answers though.
