### ISSUE TITLE
Heroku - Error => Failed to compile

### ISSUE THREAD

**Issue by zoltanalmodo** [maxmarinich/react-alice-carousel#62]
hi!

i built a react-app
source code here:
https://github.com/zoltanalmodo/purpose-react-app

it works fine when I run it on my local repository with npm start...

HOWEVER
when I deploy to heroku it gives me the following ERROR :

Failed to compile
./src/Components/Home/HomeGallery/HomeGallery.js
Module not found: Can't resolve 'react-alice-carousel' in '/app/src/Components/Home/HomeGallery'

can you please resolve? 
I am using the latest updated version on all associated software packages.
+updated react-alice-carousel 2x

thank you.
zoltan

**Comment by maxmarinich** [comment]
Hi, @zoltanalmodo! Obviously there is not the library issue. Most likely, `react-alice-carousel` should be added to the project like a dependence (replace it from "devDependencies" to "dependencies")
