### ISSUE TITLE
Labels for prev and next buttons

### ISSUE THREAD

**Issue by mbesada** [maxmarinich/react-alice-carousel#65]
Hello there, I did an small change to set the 'Prev' and 'Next' buttons labels, I tried to do a PR but I have no access, let me know if you are interested on this, thanks!

**Comment by maxmarinich** [comment]
Hi, @mbesada! Thanks so much for your action. Your issue is a duplicate [#45](https://github.com/maxmarinich/react-alice-carousel/pull/45).
