### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by NetJS** [maxmarinich/react-alice-carousel#66]
Hello :-) Thanks for your work, I like your library!

I wanna ask about RTL
I'm creating web app with English and Arabic languages
I'm switching langs with
`<html lang="en" dir="ltr"` and `<html lang="en" dir="rtl"`

with regular LTR all works good, but when I'm switching to RTL - wierd things happened

**LTR**
![a1](https://user-images.githubusercontent.com/6763285/59944835-8af2eb80-946e-11e9-81e9-3d0faadc6a84.png)

**RTL**
![a2](https://user-images.githubusercontent.com/6763285/59944863-9514ea00-946e-11e9-8677-b100affecb17.png)

**Comment by maxmarinich** [comment]
Hi @NetJS! Gallery supports pseudo `rtl` behavior. And it provides the `autoPlayDirection` property to change the direction of the gallery during automatic playback. You can use a workaround to solve the problem, e.g.:
```js
function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <div dir="ltr">
        <AliceCarousel autoPlayDirection="rtl" autoPlay />
      </div>
    </div>
  );
}
```

**Comment by felixmosh** [comment]
`direction: rtl` breaks all the calculations of this plugin.
If it works only in ltr, it is better that the base css will include this attribute, WDYT?
