### ISSUE TITLE
Resize function fired on menu drop down

### ISSUE THREAD

**Issue by eideeivindsen** [maxmarinich/react-alice-carousel#67]
Hey! I'm testing my solution on a physical device and found that the resize function is fired when scrolling vertically on my browser. The issue seems to be the menu bar of chrome dropping down when scrolling upwards. This causes the resize function to fire and automatically reset my slider to the first index.

Is there some way to disable the responsive default behavior of the carousel. In my case, I don't really need anything to change on resize at all. Either way, a solution would be much appreciated.

**Comment by maxmarinich** [comment]
Hi @eideeivindsen! Could you provide a code sample like [here](https://codesandbox.io/)?

**Comment by eideeivindsen** [comment]
@maxmarinich there is no point in making a sandbox since the problem is only on physical devices and will not appear when emulating mobile screens. But I can try to elaborate a bit further:

https://i.stack.imgur.com/hpiFp.gif
In the example above you can see how the menu bar hides when scrolling down and shows when scrolling up. This causes the view height of the screen to change. This again will cause a window.resize function to fire. Because of the carousel' responsive design, it will render the first item in the carousel when the screen is resized. The effect of this is that whenever scrolling vertically on a mobile, the menu bar will show/hide and cause the carousel to reset to the first item.

This article elaborates further on the mobile view height problem: https://css-tricks.com/the-trick-to-viewport-units-on-mobile/.

**Comment by maxmarinich** [comment]
I know how it works I try get real code sample with gallery instance.

**Comment by eideeivindsen** [comment]
https://codesandbox.io/embed/blissful-mccarthy-br8u2
Here is a code example that works the same way as my application with the real data switched with dummy data. The behaviour is the same.

**Comment by maxmarinich** [comment]
@eideeivindsen, upd to [v1.15.0](https://github.com/maxmarinich/react-alice-carousel/commit/168322f78cd4f93073dbeee3c6d56ac5b1028869)
1. Add new property `shouldHandleResizeEvent`
2. Resize problem fixes
