### ISSUE TITLE
Make _slideNext/_slidePrev functions accessible 

### ISSUE THREAD

**Issue by Henriklimseth** [maxmarinich/react-alice-carousel#69]
I have a React/TypeScript project where I want to use alice-carousel with custom next/prev buttons. To do this I need to be able to access the _slideNext and _slidePrev functions used within AliceCarousel, but they are not exposed in TypeScript.

My current workaround is a custom `.d.ts`-file:
```
import ReactAliceCarousel from 'react-alice-carousel';

declare module 'react-alice-carousel' {
  // tslint:disable-next-line variable-name
  export class Carousel extends ReactAliceCarousel {
    _slidePrev();
    _slideNext();
  }
}
```
And using the `Carousel` class. I'd rather not do that as it is quite fragile to updates in your library.
Are there any plans to also expose these functions in TS, or do you have a better workaround?

**Comment by maxmarinich** [comment]
Hi, @Henriklimseth! Try [this](https://codesandbox.io/s/reactalicecarousel-typescript-example-y7obi) example.

**Comment by Henriklimseth** [comment]
Thank you for the response @maxmarinich , the sandbox is much appreciated!
However, typecasting `Carousel` as  `any` doesn't solve my issue. There's no type security for the functions, and calls to `_slideNext`/`_slidePrev` are still vulnerable to a patch update on your end. 
Are there any plans to include these functions on the type of the `AliceCarousel` class?

**Comment by maxmarinich** [comment]
will added in a next version

**Comment by maxmarinich** [comment]
added in [v1.15.2](https://github.com/maxmarinich/react-alice-carousel/commit/41e57e302aa8cb768fe8b96493a8da368691f79b), see [docs](https://github.com/maxmarinich/react-alice-carousel#methods)
