### ISSUE TITLE
Any way to reset auto play timer when i click next button/prev button?

### ISSUE THREAD

**Issue by z3r0c00l-2k** [maxmarinich/react-alice-carousel#70]
I have this Carousel component with autoplay(delay of 6000) and next/prev buttons.
When I navigate with the buttons, item changes quickly after the `autoPlayInterval`.
This weird. Any way to fix this issue?
Any way to reset the `autoPlayInterval` timer when I click on next/prev buttons.

**Comment by maxmarinich** [comment]
Hello@ z3r0c00l-2k! the `AutoPlay` behavior will improve in one of the following versions.  To reset autoplay use `disableAutoPlayOnAction` property.
