### ISSUE TITLE
CSS Transform makes content of the slider blurry

### ISSUE THREAD

**Issue by pitkes22** [maxmarinich/react-alice-carousel#72]
Hello, I have a small problem with my carousel.
Sometimes the value of Transform-translate3d property on stage element is not a round number in X-axes. When this happens it makes the content of the slider blurry in some browsers(chrome).
It would be great to have the option to round the offset or do it by default.

**Comment by maxmarinich** [comment]
Hi, @pitkes22! Could you provide a code sample?

**Comment by pitkes22** [comment]
Hi, sorry for the late response. 🏖️
I don't think that a code sample would help. This behavior can be observed on any example when you move it into a position where the value of `translate3d` is not a whole number.
This is most noticeable when you have a thin line. For example on the text.

Here is an example of how it looks in different browsers:
![example](https://i.imgur.com/fUjsGQk.gif)

As you can see, in chrome, when you translate element by not whole pixel it will interpolate it. This will result in slightly blurry content of the carousel.
The easiest way to fix this and have the same result as in firefox is to round the value of `transform3d`.

**Comment by maxmarinich** [comment]
@pitkes22, after a little research, I think the problem is part of the browser's behavior. And  it would be strange to try to find workarounds for this problem by changing the existing behavior of the library.

**Comment by maxmarinich** [comment]
@pitkes22, add  `backface-visibility: hidden` property for a gallery item. It should resolve the issue.

**Comment by pitkes22** [comment]
@maxmarinich Thank you, but it don't work for me. Only CSS property that helped with the issue is `transform-style: preserve-3d` on stage element. But I can't use it because I use [Tilt Effect](https://micku7zu.github.io/vanilla-tilt.js/) on gallery items and it breaks when I apply this property. (Tilt effect does not cause the issue, I tried it without it and it was the same)
