### ISSUE TITLE
Less dots when multiple items are displayed

### ISSUE THREAD

**Issue by AmazingTurtle** [maxmarinich/react-alice-carousel#74]
Is this supposd to be?
Using responsive items set to 3 I have only 1/3 of dots.

See the following screenshot
![grafik](https://user-images.githubusercontent.com/2357438/61876079-4c78a280-aeec-11e9-9044-7900e4243be1.png)

Is there any way to get achieve the desired behaviour of dots showing 1 dot for each entry no matter how many items are shown per slide?

**Comment by maxmarinich** [comment]
Hi, @AmazingTurtle! To create an expected behavior use `custom dots navigation` like [here](https://codesandbox.io/s/reactalicecarousel-typescript-example-y7obi).
