### ISSUE TITLE
--save-dev in the Readme

### ISSUE THREAD

**Issue by naorzr** [maxmarinich/react-alice-carousel#75]
Hey!

I was wondering, why the -dev flag is turned in the code snippet for installing this lib?
is that a typo?

**Comment by maxmarinich** [comment]
Hi @naorzr, by default you no need install the lib as dependency.

**Comment by naorzr** [comment]
@maxmarinich Am I missing something? why is that?

**Comment by maxmarinich** [comment]
flag `--save-dev ` - for example, you develop your own library and use the gallery only for the prototype of some screens for demonstration (development mode). 
flag` --save ` - if the gallery is a part of your library (your library cannot work without this dependency)

**Comment by naorzr** [comment]
of course, it's just that it's common that libraries like this will be used not for dev purposes, so it'd be best to just leave the -dev flag out.
it made me think this lib isn't production ready or something like that.

anyway, nice library and thank you for the contribution!

**Comment by maxmarinich** [comment]
the best way to check if a library is ready to work is to use [Semantic Versioning](https://semver.org)

anyway, the documentation has been updated for v1.15.3
thanks for participating
