### ISSUE TITLE
Callback to trigger resize event?

### ISSUE THREAD

**Issue by Runecreed** [maxmarinich/react-alice-carousel#78]
Is there a way to force the carousel to do a resize?
Seems that within my app if I move to a different page the initial size of the carousel is smaller than it is supposed to be - it fixes itself when I refresh the page (or navigate again),

Im guessing it doesn't get a resize event from jumping using React Router links, hopefully it'll fix itself if I could trigger a resize once it has been initialized

I noticed the prop onInitialized, but how do I use it to trigger a resize event?

Thanks!

**Comment by maxmarinich** [comment]
Hi @Runecreed! It works like this - the onResize gallery checks if the scene dimensions has been changed. And if the value is true, the gallery props will be recounted. Probably your shell component has not been changed. From [docs](https://github.com/maxmarinich/react-alice-carousel#props) - use the `shouldHandleResizeEvent` property to change a basic behavior.
