### ISSUE TITLE
How to display carousel items with flexible width and fixed space between?

### ISSUE THREAD

**Issue by Nogias9x** [maxmarinich/react-alice-carousel#79]
Hi @maxmarinich,

I really appreciate your works here for this awesome library.
I'm using it and everything is good. Thank you again.

But I have a UI issue, and don't know how to config it. I think it may be a feature request.
We are implement a carousel likes Google. When you search images, Google shows you groups of result likes this   
![image](https://user-images.githubusercontent.com/11822492/64248059-6caf6e80-cf3a-11e9-9055-75e72b3afa7c.png)
Each item may have different width, and if there's just a couple of items, the items are float left with a fixed right-margin likes this
![image](https://user-images.githubusercontent.com/11822492/64248436-450cd600-cf3b-11e9-97e3-6eebb3a14835.png)

My current configuration lead me to this:
![image](https://user-images.githubusercontent.com/11822492/64247794-cebba400-cf39-11e9-9052-aab4b087537b.png)
```js
const itemMaxWidthPx = remToPx(itemMaxWidthRem);
  const stagePaddingRight = itemMaxWidthPx / 3;
  const itemsPerSlideConfigs = { 0: { items: 1 } };
  for (let itemsNumber = 1; itemsNumber <= itemsComponents.length; itemsNumber++) {
    const minScreenWidth = 1.1 * itemsNumber * itemMaxWidthPx + stagePaddingRight;
    itemsPerSlideConfigs[minScreenWidth] = { items: itemsNumber };
  }
  const stagePaddingConfigs = {
    paddingLeft: 0,
    paddingRight: stagePaddingRight,
  };

<AliceCarousel
        infinite={false}
        mouseDragEnabled
        autoHeight
        buttonsDisabled
        dotsDisabled
        responsive={itemsPerSlideConfigs}
        stagePadding={stagePaddingConfigs}
        onInitialized={onInitialized}
        onSlideChanged={onSlideChanged}
        children={itemsComponents}
      />
```

Is there any way we can:
+ have flexible width items
+ have displayed items like overflow-hidden, no need to specify responsive
+ have items float left (specially when we just have a few items)

Thank you for reading this

**Comment by maxmarinich** [comment]
Hi, @Nogias9x! The current version has not that functionalityHi, @Nogias9x! The current version doesn't have this functionality. It will be implemented in future versions.

**Comment by Nogias9x** [comment]
Hi @maxmarinich,

Thank for the response. I worked around for it. Here is my solution. I'd love to share if anyone need it.
 Its effects:
- Make items have flexible width
- Make items have fixed margin
Meaning: Let active(displaying) and stage (tails-preparing to display) items have flex width. The clone (viewed-hidden) items should have fixed width (otherwise your carousel will be mess)

**Side-effect:** if you are computing if the last item/slide is viewed, this approach may lead to incorrectly computation due to the flexible width. This side-effect is not critical to me, but please consider if you are intending to using this approach. 

```js
const Wrapper = styled.div`
  width: 100%;
  
  li.alice-carousel__stage-item :not(.__cloned) {
    width: auto !important;
    margin-right: 1rem;
  }
`;
return (
    <Wrapper>
      <AliceCarousel
        ref={ref}
        infinite={false}
        mouseDragEnabled
        autoHeight
        buttonsDisabled
        dotsDisabled
        responsive={itemsPerSlideConfigs}
        stagePadding={stagePaddingConfigs}
        onInitialized={onInitialized}
        onSlideChanged={onSlideChanged}
        children={itemsComponents} // you should set style={maxWidth: itemMaxWidthPx} for every items
      />
    </Wrapper>
  );
```
I hope it helps.
Have a good day @maxmarinich

**Comment by sharmistha071** [comment]
Hi @maxmarinich, 
Is there any update of this feature request?

**Comment by maxmarinich** [comment]
Hello, @sharmistha071! I hope will be soon. Now I'm focused on improving and test coverage.

**Comment by markdegroat** [comment]
@Nogias9x that solution worked wonderfully - thank you for posting

**Comment by maxmarinich** [comment]
Hi, there! Please check live [demo](https://maxmarinich.github.io/react-alice-carousel/static/#auto-width) and new version of library.
