### ISSUE TITLE
Carousel ignores slideToIndex prop

### ISSUE THREAD

**Issue by lianulloa** [maxmarinich/react-alice-carousel#80]
Hi, I'm using the carousel with this configuration:

    <Carousel ref="carousel"
        dotsDisabled={true}
	buttonsDisabled={true}
	items={slides}
	onSlideChanged={()=>console.log('changed')}
	keysControlDisabled={true}
	slideToIndex={this.state.index}
	/>

but it is ignoring what is passed through _slideToIndex_ prop. Besides, whenever parent component change its state the carousel gets rerendered and therefore returns to slide 0

How can I fix this? Thanks

**Comment by maxmarinich** [comment]
Hi, @lianulloa! Please provide a complete code example.
