### ISSUE TITLE
Dot transitions not playing when onSlideChanged calls a location change

### ISSUE THREAD

**Issue by flo-wolf** [maxmarinich/react-alice-carousel#81]
I am not sure why this is happening, but it is.
When changing the location using react-router-dom in the onSlideChanged callback (doesn't matter if using history.push or Redirect, both cause the same problem) the dot animation (fade in/out of dots) when dragging through the slides doesn't play, it is an instant switch.
However, clicking on another dot plays the animation and also changes the path, just how it should work. The problem is caused by the drag somehow.

```
onSlideChanged = (e) => {
    this.props.history.push("/testpage");
}

<AliceCarousel
                        onSlideChange={this.onSlideChanged}
                        mouseDragEnabled
                        buttonsDisabled={true}
                        items={galleryItems}
 />
```
When I remove the history.push, i.e. when the location doesn't change, it works.
The problem is not caused by the alice carousel being wrapped in a router, because it isn't. The carousel is a top level element, which doesn't re render on route change, I checked that. Only the _active class on the dots updates, as it should.

Any ideas to why this could be the case? Is the alice carousel somewhere checking the location during a drag?

**Comment by maxmarinich** [comment]
Hi, @flo-wolf! Please, provide the full code sample(here or Sandbox).

**Comment by maxmarinich** [comment]
In any case, I think your application is wrapped with a <Router> component at the top level. This updates the <AppRoot> component each time the route changes.
