### ISSUE TITLE
disable width calculation of item

### ISSUE THREAD

**Issue by younes0** [maxmarinich/react-alice-carousel#82]
is it possible to disable width calculation of Item (`.alice-carousel__stage-item`) ?
in my case, i have no drawbacks when setting width to 100% via CSS
but since inline-style is applied before stylesheet rule, there's a unwanted transition

**Comment by maxmarinich** [comment]
Hi, @younes0! No, you can't. The ability to do this will be implemented in future versions.

**Comment by younes0** [comment]
Solved the problem by rendering the sub Carousel when the slide is rendered, using https://github.com/researchgate/react-intersection-observer
