### ISSUE TITLE
How to use it as child 

### ISSUE THREAD

**Issue by skyrbs** [maxmarinich/react-alice-carousel#84]
Hello Guys,
                  I am getting following error message

 **"Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it."**

Below is my code example..

**HomeBanner.js**
import React from 'react';
import AliceCarousel from 'react-alice-carousel';
import "react-alice-carousel/lib/alice-carousel.css"; 
const Gallery = () => {
  const handleOnDragStart = e => e.preventDefault()
  return (
    <AliceCarousel mouseDragEnabled >
      <img src="/src/" onDragStart={handleOnDragStart} className="yours-custom-class" />
      <img src="/src/" onDragStart={handleOnDragStart} className="yours-custom-class" />
      <img src="/src/" onDragStart={handleOnDragStart} className="yours-custom-class" />
      <img src="/src/" onDragStart={handleOnDragStart} className="yours-custom-class" />
      <img src="/src/" onDragStart={handleOnDragStart} className="yours-custom-class" />
    </AliceCarousel>
  )
}

export default Gallery;

Trying to use above code in **Layout.js** Layout code is 

import React from "react";
import MetaTags from 'react-meta-tags';
import "../styles.css";
import logo from '../img/logo192.png'
import Gallery from "./HomeBanner";

const Layout = ({
    title = "Title",
    description = "Description",
    className,
    children
}) => (
    <div>
        <MetaTags>
            <title>{title}</title>
            <meta name="description" content={description} />
            <meta property="og:title" content={title} />
            <meta property="og:image" content={logo} />
        </MetaTags>  
         {Gallery} 
        <div className={className}>{children}</div>
    </div>
);
export default Layout;

This layout has been called in Homepage...

Can you please let me know what am i missing ?

**Comment by maxmarinich** [comment]
Hi, @skyrbs! Use like valid child: 
`<Gallery />`
