### ISSUE TITLE
Latest React, Typescript - Cannot read property 'array' of undefined.

### ISSUE THREAD

**Issue by owlyowl** [maxmarinich/react-alice-carousel#85]
Hi we're using latest react and typescript.

When we include the most basic example from your https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-alice-carousel/react-alice-carousel-tests.tsx

We get the exception cannot read property 'array' of undefined.

Would love some help

**Comment by maxmarinich** [comment]
Hi, @owlyowl! Works like expected, see [sandbox](https://codesandbox.io/s/ts-example-x2j7k). If not - create own sandbox with a full code sample.
