### ISSUE TITLE
Scroll by more than 1 item

### ISSUE THREAD

**Issue by holtc** [maxmarinich/react-alice-carousel#90]
Is there a prop or something I can pass in order to scroll more than 1 slide at a time?  Perhaps adding to the `responsive` prop? I'm thinking something along the lines of:

```
const responsive = {
  0: {
    items: 1,
    numToSlide: 1
  },
  1024: {
    items: 2,
    numToSlide: 2
  },
  1200: {
    items: 3,
    numToSlide: 3
  }
}
```

**Comment by maxmarinich** [comment]
Hi, @holtc! Yes you can. You can use for that `slideTo` method or `slideToIndex` property. See [example](https://github.com/maxmarinich/react-alice-carousel#custom-prev--next-buttons-dots--thumbs-navigation).

**Comment by holtc** [comment]
Those are not the same.  I am looking for a prop that will natively scroll that number of slides without me having to override the slide functions.  Something like `slidesToSlide` from https://www.npmjs.com/package/react-multi-carousel#specific-props

**Comment by maxmarinich** [comment]
Gallery doesn't have such functionality. Because it's redundant. You can implement the exact behavior using the properties I specified.

**Comment by holtc** [comment]
I disagree that it is redundant, will create a fork to support this

**Comment by FutureKode** [comment]
@holtc Hello, I'm looking for this functionality too, did you create the fork to add this?
