### ISSUE TITLE
AutoPlay INterval is not working in Gatsby App

### ISSUE THREAD

**Issue by arhoy** [maxmarinich/react-alice-carousel#91]
I am not able to get autoPlayInterval prop to work... everything else seems to be working fine

     <AliceCarousel
          mouseDragEnabled
          buttonsDisabled
          autoPlay={loop}
          stopAutoPlayOnHover={true}
          duration={2000}
          autoPlayInterval={1000}
          autoPlayDirection="rtl"
        >

Any suggestions?
Repo: 
https://github.com/arhoy/fashion-two/blob/master/src/components/reusableStyles/carousel/AliceGallery.js

**Comment by maxmarinich** [comment]
Hi, @arhoy! Please, provide an example [here](https://codesandbox.io/).

**Comment by maxmarinich** [comment]
@arhoy, basically this feature works outside of the Gatsby App. I think it's not a library issue. I will soon improve the "autoplay" mechanism. I hope this helps.
