### ISSUE TITLE
Option to hide dots if all items visible

### ISSUE THREAD

**Issue by benhodgson87** [maxmarinich/react-alice-carousel#93]
Currently if all items are visible a single dot is still shown beneath.

eg. We have 4 items - we show 2 at handheld breakpoints, and all 4 on desktop. There is no carousel functionality at desktop, therefore the dot is redundant for desktop users.

It would be useful to provide a prop, eg. `dotsDisabledIfAllVisible` to toggle behaviour that would hide the dots if all items are currently visible.

Currently the only way to achieve this is by setting CSS locally, targetting the class on the dot container to hide it at the same breakpoint - however this will break if additional items are added but the media query is not updated to start showing the dot container. It would be better to let the carousel itself work out whether or not to display this.

**Comment by benhodgson87** [comment]
Happy to look into a PR for this

**Comment by maxmarinich** [comment]
Hi, @benhodgson87! There is a solution for your case. But it includes additional handlers and may seem redundant. If you need this solution now, please let me know. Or wait a bit, I'll add the property in the next release.

**Comment by maxmarinich** [comment]
@benhodgson87, added in [v1.17](https://www.npmjs.com/package/react-alice-carousel). Set `controlsStrategy="responsive"` property.

**Comment by RaghavDoc32** [comment]
Hi @maxmarinich @benhodgson87
i can see controlsStrategy="responsive" is working only if responsive object passed, is it possible to do without responsive obj, (as i m handling width of each item)?
