### ISSUE TITLE
Can you fill out the form and see the data on the next page?

### ISSUE THREAD

**Issue by jacektessen** [maxmarinich/react-alice-carousel#94]
Hi!!

I have prepared a very simple example: 

https://codesandbox.io/s/adoring-cerf-q9ru6

**Comment by maxmarinich** [comment]
Hi, @jacektessen! You have some bugs. Take my [example](https://codesandbox.io/s/icy-forest-cshyc)!

**Comment by jacektessen** [comment]
@maxmarinich Thanks!!!

**Comment by jacektessen** [comment]
Hi, @maxmarinich. There is another problem. Now when I update the state in the parent (when fill out the form and submit), carousel backs to the first slide, even if currentIndex is correct. I made a simple example:

https://codesandbox.io/s/adoring-cerf-q9ru6

**Comment by maxmarinich** [comment]
I hope this helps. Use the next [example](https://codesandbox.io/s/km2n35kq3v).
