### ISSUE TITLE
Next/Previous should be button elements

### ISSUE THREAD

**Issue by Luphrid** [maxmarinich/react-alice-carousel#96]
This is a great plugin.  One suggestion I have is making the prev/next controls button elements (or adding the appropriate button roles).  They are not currently reachable via keyboard tabbing. 

I realize custom buttons can be added with the use of slideNext() and slidePrev() as the onClick.  However, I am running into issues getting the itemInfo of the carousel in onInitialized.  The ref to the carousel is not yet available.

```JSX
import React, {Component} from 'react';
import AliceCarousel from 'react-alice-carousel'
import * as Utils from 'react-alice-carousel/lib/utils';

export default class Carousel extends Component {

  updateButtonVisibility = () => {
    const itemInfo = Utils.itemInfo(this.Carousel.state); /* Breaks because this.Carousel ref is not yet populated when onInitialized is called. */
    this.setState({isPrevSlideDisabled: itemInfo.isPrevSlideDisabled, isNextSlideDisabled: itemInfo.isNextSlideDisabled});
  };

  render() {

    return (
      <div className="carousel">
        <AliceCarousel
            items={this.props.items}
            dotsDisabled={true}
            buttonsDisabled={true}
            ref={node => this.Carousel = node}
            onSlideChanged={this.updateButtonVisibility}
            onInitialized={this.onInitialized}
        />
        {!this.state.isPrevSlideDisabled &&
        <button className="alice-carousel__prev-btn" onClick={() => this.Carousel.slidePrev()} aria-label="Previous Slide"></button>
        }
        {!this.state.isNextSlideDisabled &&
        <button className="alice-carousel__next-btn" onClick={() => this.Carousel.slideNext()} aria-label="Next Slide"></button>
        }
      </div>
    );
  }
}
```

**Comment by maxmarinich** [comment]
Hi, @Luphrid! This behavior is the default for components. At first there is invoked componentDidMount from AliceCarousel, then componentDidMount from Carousel. Refs are available after mounting only. When the onInitialized method is called, the Carousel has no references because it is not mounted yet at that point.

Also it is a bad practice, you've use encapsulated methods(from utils). You should find the more elegant solution. 

In the next version, I will extend EventObject with the properties you need.

**Comment by Luphrid** [comment]
@maxmarinich Thank you for your response.  I am glad you plan to extend the EventObject with the additional fields from itemInfo.  

Oh yeah, and trust me, I did not want to use the encapsulated methods.

**Comment by maxmarinich** [comment]
@Luphrid, added in [v1.17](https://github.com/maxmarinich/react-alice-carousel/commit/aeb49051f569d1541fefb87935e5ed10e97538c7)

**Comment by Luphrid** [comment]
Thank you!
