### ISSUE TITLE
mouseTrackingEnabled only allows mouse drag on item, not item's inner elements

### ISSUE THREAD

**Issue by Luphrid** [maxmarinich/react-alice-carousel#97]
When mouse tracking is enabled, I get strange dragging behavior.  Using the cursor, I can only drag when clicking a staged item with no inner elements.  If the staged item has inner elements (e.g. img, a, etc), attempting to drag does not work until mouseup.

Current behavior: Mousedown, mouseup, hover moves slider
Expected behavior: Mousedown, drag moves slider, mouseup, dragging disabled (similar to https://owlcarousel2.github.io/OwlCarousel2/demos/basic.html)

**Comment by maxmarinich** [comment]
@Luphrid, Please provide a code sample like [this](https://codesandbox.io/s/zrlmr3p61m).

**Comment by Luphrid** [comment]
@maxmarinich Thank you for the example code sandbox.  I was using items prop.  So I overlooked the onDragStart handler in your docs.  However, if the item is a link, the link can still be clicked after dragging.  To reproduce, start dragging a slide, and finish dragging while hovering over the same slide.

Here is my [sample](https://codesandbox.io/s/react-alice-carousel-stage-padding-example-heo49?fontsize=14).

**Comment by maxmarinich** [comment]
@Luphrid, this is the expected behavior if we are talking about mouse handlers. If we have a link, we should be able to click on it. Here we are faced, rather, with erroneous decisions of the UI. And in this case you should handle actions independently. The solution:

```js
const COORDS = {
   xDown: null,
   xUp: null
}

const handleOnMouseDown = e => {
  e.preventDefault()
  COORDS.xUp = null
  COORDS.xDown = null
  
  COORDS.xDown = e.clientX
}

const handleMouseUp = e => {
  e.preventDefault()
  COORDS.xUp = e.clientX
}

const handleOnClick = e => {
  if (COORDS.xDown !== COORDS.xUp) {
    e.preventDefault()
    console.log('drag')
  } else {
    console.log('click')
  }
}
  
   // ... code before
          <a
            href="/"
            onMouseDown={handleOnMouseDown}
            onMouseUp={handleMouseUp}
            onClick={handleOnClick}
          >
            <img alt="" key={picture} src={picture} style={{ width: "100%" }} />
          </a>

  // ...code after
```
